<a href="https://colab.research.google.com/github/Abhishek3102/ML/blob/main/MOVIE_RECOMMENDATION_SYSTEM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
df = pd.read_csv("/content/movies.csv")

In [46]:
df.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton

In [47]:
df.tail()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [48]:
# df = df.drop(columns="index", axis=1)

In [49]:
df

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4798,4798,220000,Action Crime Thriller,NaN,9367,united states\u2013mexico barrier legs arms pa...,es,El Mariachi,El Mariachi just wants to play his guitar and ...,14.269792,...,81.0,"[{""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,"He didn't come looking for trouble, but troubl...",El Mariachi,6.6,238,Carlos Gallardo Jaime de Hoyos Peter Marquardt...,"[{'name': 'Robert Rodriguez', 'gender': 0, 'de...",Robert Rodriguez
4799,4799,9000,Comedy Romance,NaN,72766,NaN,en,Newlyweds,A newlywed couple's honeymoon is upended by th...,0.642552,...,85.0,[],Released,A newlywed couple's honeymoon is upended by th...,Newlyweds,5.9,5,Edward Burns Kerry Bish\u00e9 Marsha Dietlein ...,"[{'name': 'Edward Burns', 'gender': 2, 'depart...",Edward Burns
4800,4800,0,Comedy Drama Romance TV Movie,http://www.hallmarkchannel.com/signedsealeddel...,231617,date love at first sight narration investigati...,en,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...",1.444476,...,120.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,"Signed, Sealed, Delivered",7.0,6,Eric Mabius Kristin Booth Crystal Lowe Geoff G...,"[{'name': 'Carla Hetland', 'gender': 0, 'depar...",Scott Smith
4801,4801,0,NaN,http://shanghaicalling.com/,126186,NaN,en,Shanghai Calling,When ambitious New York attorney Sam is sent t...,0.857008,...,98.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A New Yorker in Shanghai,Shanghai Calling,5.7,7,Daniel Henney Eliza Coupe Bill Paxton Alan Ruc...,"[{'name': 'Daniel Hsia', 'gender': 2, 'departm...",Daniel Hsia
4802,4802,0,Documentary,NaN,25975,obsession camcorder crush dream girl,en,My Date with Drew,Ever since the second grade when he first saw ...,1.929883,...,90.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Date with Drew,6.3,16,Drew Barrymore Brian Herzlinger Corey Feldman ...,"[{'name': 'Clark Peterson', 'gender': 2, 'depa...",Brian Herzlinger

In [50]:
m = df.value_counts().unique()
print(m)

[1]

In [51]:
df.shape

(4803, 24)

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   index                 4803 non-null   int64
 1   budget                4803 non-null   int64
 2   genres                4775 non-null   object
 3   homepage              1712 non-null   object
 4   id                    4803 non-null   int64
 5   keywords              4391 non-null   object
 6   original_language     4803 non-null   object
 7   original_title        4803 non-null   object
 8   overview              4800 non-null   object
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object
 11  production_countries  4803 non-null   object
 12  release_date          4802 non-null   object
 13  revenue               4803 non-null   int64
 14  runtime               4801 non-null   float64
 15  spoken_languages      4803 non-null   object
 16  status                4803 non-null   object
 17  tagline               3959 non-null   object
 18  title                 4803 non-null   object
 19  vote_average          4803 non-null   float64
 20  vote_count            4803 non-null   int64
 21  cast                  4760 non-null   object
 22  crew                  4803 non-null   object
 23  director              4773 non-null   object
dtypes: float64(3), int64(5), object(16)
memory usage: 900.7+ KB

In [53]:
df.describe()

,index,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4803.000000,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2401.000000,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,1386.651002,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,1200.500000,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,2401.000000,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,3601.500000,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,4802.000000,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

In [54]:
for types in df["genres"].unique():
  print(types)

Action Adventure Fantasy Science Fiction
Adventure Fantasy Action
Action Adventure Crime
Action Crime Drama Thriller
Action Adventure Science Fiction
Fantasy Action Adventure
Animation Family
Adventure Fantasy Family
Action Adventure Fantasy
Adventure Fantasy Action Science Fiction
Adventure Action Thriller Crime
Action Adventure Western
Adventure Family Fantasy
Science Fiction Action Adventure
Adventure Action Fantasy
Action Comedy Science Fiction
Action Adventure
Adventure Fantasy
Adventure Drama Action
Drama Romance Thriller
Adventure Action Science Fiction
Thriller Action Adventure Science Fiction
Action Adventure Science Fiction Thriller
Action Adventure Thriller
Family Fantasy Adventure
Adventure Action Science Fiction Thriller
Fantasy Adventure Family
Animation Family Adventure Comedy
Adventure Action Thriller Science Fiction
Animation Family Comedy
Action Science Fiction Thriller
Action
Action Drama Horror Science Fiction Thriller
Action Family Fantasy
Drama Romance
Adventure Fantasy Action Romance
Action Science Fiction Adventure
Adventure Action
Adventure Animation Family
Animation Adventure Comedy Family Action
Action Comedy Crime Thriller
Animation Drama
Science Fiction Fantasy Action Adventure
Science Fiction
Drama Action Crime Thriller
Animation Comedy Family Adventure
Animation Family Adventure Science Fiction
Adventure Drama Family
Action Adventure Comedy Science Fiction Western
Action Adventure Crime Fantasy Science Fiction
Fantasy Comedy Family
Action Science Fiction
Drama Comedy Animation Family
Family Adventure Drama Fantasy
Adventure Fantasy Drama
Fantasy Adventure Action Family Romance
Science Fiction Action Drama Thriller
Action Adventure Science Fiction Romance
Drama Action Adventure Fantasy
Comedy Adventure Fantasy Animation Family
Adventure Family Mystery Science Fiction
Adventure Family Animation Action Comedy
Family Animation Comedy Adventure
Adventure Animation Family Fantasy
Fantasy Adventure Animation Family
Action Thriller Science Fiction
Adventure Drama Science Fiction
Action Thriller Science Fiction Mystery Adventure
Action Adventure Drama Horror Science Fiction
Action Crime Thriller
Fantasy Drama Thriller Mystery Romance
Fantasy Adventure Action Comedy Drama
Adventure Action Drama Thriller
Fantasy
Fantasy Adventure Animation Comedy Family
Science Fiction Action Thriller Adventure
History Romance War
Adventure Science Fiction Action
War History Action Adventure Drama
Adventure Fantasy Family Mystery
Fantasy Action
Drama Horror Action Thriller Science Fiction
Adventure Comedy Family Fantasy
Animation Comedy Family Fantasy
Action Crime Drama
Family Animation
Adventure Fantasy Action Comedy Family
Animation Adventure Family
Thriller Mystery
Fantasy Action Adventure Family Comedy
Adventure
Comedy Fantasy
Drama Horror Thriller
Family Animation Adventure Comedy
Action Adventure Family Fantasy
Adventure Action Thriller
Action Drama Thriller
Adventure Animation Comedy Family
Adventure Drama War
Action Fantasy Comedy
Action Thriller Science Fiction Adventure
Action Adventure Comedy Science Fiction
Adventure Action Animation
Action Adventure Animation Comedy Family
Action Thriller Adventure
Fantasy Animation Family
Comedy
Drama Action War History
Fantasy Action Adventure Animation Comedy
Action Mystery Science Fiction
Action Adventure Comedy Crime Thriller
Drama Action Science Fiction
Action Adventure Comedy Drama Mystery
Adventure Action Animation Fantasy Science Fiction
Adventure Fantasy Drama Romance
Animation Comedy Family
Western Drama Adventure Thriller
Animation Comedy Family Western Adventure
Action Drama Mystery Thriller
Adventure Animation Family Comedy
Fantasy Comedy Animation Science Fiction Family
Adventure Thriller Science Fiction
Adventure Action Comedy Thriller Crime
Action Adventure Animation Family Fantasy
Action Mystery Thriller
Drama Adventure
Adventure Animation Mystery
Drama
Adventure Comedy Fantasy Family
Animation Action Comedy Family Science Fiction
Fantasy Action Comedy Crime
Science Fiction Adventure Thriller
Animation Adventure Comedy Family
Action Thriller Crime
Adventure Action Crime Mystery
Action Thriller
Action Crime Fantasy
Family Comedy Fantasy
Adventure Fantasy Action Thriller
Thriller Action Fantasy Horror
Action Adventure Comedy
Science Fiction Adventure Mystery
Family Adventure Animation Comedy
Action Family Science Fiction
Comedy Drama Romance
Action Comedy
Action Science Fiction Adventure Mystery
Science Fiction Adventure Action
Action Science Fiction Adventure Fantasy
Adventure Animation Comedy Family Fantasy
Fantasy Adventure Comedy Family
Drama Action History War
Action Adventure Drama
Science Fiction Action Adventure Fantasy Comedy
Science Fiction Thriller Drama
Fantasy Action Adventure Comedy
Action Adventure Comedy Family Fantasy
Drama History War Action
Thriller Crime
Action Comedy Drama Thriller
Adventure Science Fiction Thriller
Action Crime Comedy
Action War
Animation Family Adventure Comedy Fantasy
Adventure Science Fiction
Action Science Fiction Drama
Fantasy Family Comedy Animation
Comedy Fantasy Family
Drama Action Adventure History War
Animation Fantasy Family Comedy
Romance Family Animation Music
Drama Adventure Science Fiction
Comedy Romance
Action Drama Adventure
Action Thriller Science Fiction Mystery
Thriller Science Fiction Action Adventure
History Crime Drama
Drama Crime
Thriller Drama Crime
Action Comedy Crime
Drama Western
Drama Animation Family
Adventure Action Thriller Mystery
Fantasy Action Adventure Family
Family Fantasy
Animation Adventure Family Fantasy
Action Thriller Romance
Action Fantasy Horror Mystery
Drama Thriller Action
Crime Drama Comedy
Drama Science Fiction
Action Crime
Adventure Animation Family Fantasy Science Fiction
Adventure Comedy Science Fiction
Fantasy Comedy Family Adventure
Thriller Drama Adventure Action History
War Action Adventure Drama Thriller
Animation
Crime Drama Mystery Thriller
Drama History Crime
Drama History War
Action History War
Adventure Fantasy Action Thriller Science Fiction
Animation Comedy Adventure Family
Romance Fantasy Family Drama
Fantasy Drama
Thriller Science Fiction Drama Mystery
Thriller Action Drama Science Fiction
Western History War
Action Adventure Animation Family
Drama Horror Mystery Thriller
Adventure Comedy Drama Fantasy
Drama Thriller Crime
Animation Family Adventure
Thriller Crime Mystery Drama
Action Adventure Crime Mystery
Drama Thriller History War
Comedy Action
Drama Science Fiction Adventure
Thriller Fantasy Comedy Family Mystery
Drama Science Fiction Mystery
Crime Thriller
Action Adventure Fantasy Thriller
Action Adventure Comedy Crime Mystery
Thriller Action Romance Science Fiction Adventure
Comedy Science Fiction
Crime Thriller Drama
Drama History Thriller
Romance Drama History
Fantasy Action Family
Drama History
Adventure Drama
Animation Comedy
Comedy Family Fantasy Romance
Comedy Family
War
Adventure Action Comedy Thriller
Drama History Romance
Drama Animation Family Comedy
Fantasy Drama Mystery
Action Thriller Drama
Drama Music
Adventure Fantasy Drama Comedy Science Fiction
Action Thriller Adventure Science Fiction
Fantasy Comedy Romance Science Fiction
Mystery Adventure Comedy
Comedy Drama Fantasy Romance
Horror Comedy Fantasy
Adventure Fantasy Science Fiction
Fantasy Comedy
Thriller Adventure Action
Science Fiction Adventure Fantasy
Action Fantasy
Comedy Animation Family
Comedy Family Fantasy
Action Drama Romance
Comedy Drama
Comedy Fantasy Family Music Animation
Action Comedy Thriller
Drama Comedy Romance
Drama Thriller Mystery
Comedy Romance Drama
Animation Comedy Family Science Fiction
Action Crime Science Fiction Thriller
Fantasy Comedy Family Romance
Thriller Crime Drama
Romance Comedy
Mystery Thriller Action
Comedy Family Science Fiction
Horror Thriller Fantasy Mystery
Animation Comedy Drama Family Fantasy
Action Comedy Crime Mystery Family
Drama Science Fiction Thriller
War Drama Action
Action Adventure Comedy Romance
Comedy Family Animation Adventure
Western Animation Adventure Comedy Family
Comedy Romance Family
Adventure Family Science Fiction
Romance Drama
Animation Family Music
Drama Fantasy Romance
Comedy Fantasy Romance
Adventure Fantasy Action Comedy Thriller
Comedy Fantasy Science Fiction
Mystery Drama Horror
Drama Thriller
Action Science Fiction War
Drama Music Romance
Adventure Comedy Drama Family Fantasy
Thriller Action Science Fiction
Adventure Fantasy Animation Family
Documentary Family
Thriller Science Fiction Adventure Action
Action Adventure History Romance Drama
Comedy Animation
Family Animation Drama
Crime Thriller Horror
Western Adventure
Adventure Animation Fantasy
Science Fiction Thriller
Fantasy Action Thriller Science Fiction
Drama Action Thriller Science Fiction
Animation Family Comedy Adventure
Family Comedy Music Romance
Horror Mystery Thriller
Action Adventure Comedy Family
Comedy Drama History
Animation Action Comedy Family
Comedy Crime
Drama Action History Thriller
Action Drama War
Action Comedy Thriller Romance
Comedy Action Adventure
Action Comedy Crime Romance
Action Adventure Drama Romance
Fantasy Action Drama
Mystery Drama Thriller Crime
Animation Action Science Fiction Family Adventure
Action Adventure Comedy Thriller
Action War Science Fiction
Adventure Fantasy Animation Action Comedy
Action Adventure Drama Thriller
Action Fantasy Thriller
Crime Mystery
Romance Comedy Adventure
Thriller Action Drama
Comedy Family Romance Fantasy
Action Drama History War
Drama War
Drama Mystery Thriller
Drama Thriller Science Fiction Mystery
Drama Action Thriller War
Adventure Fantasy Comedy Family
Drama Mystery Romance Science Fiction Thriller
Drama Thriller Fantasy Mystery
Comedy Family Animation Fantasy Music
Science Fiction Action Adventure Thriller
War Drama History Action
Horror Action Drama Fantasy War
Drama Action Thriller Crime
Adventure Fantasy Romance Family
Adventure Drama History
Adventure Action Horror
Fantasy Action Horror
Comedy Drama Music Romance
Thriller
Adventure Animation Action Comedy Family
Animation Music Family
Crime Drama Mystery
Mystery Action Thriller Science Fiction Adventure
Crime Mystery Thriller
Adventure Fantasy Action Comedy Science Fiction
Action Drama History Thriller
Action Fantasy Horror
Romance Drama Mystery
Mystery Science Fiction Thriller
Action Adventure Fantasy War
Drama Horror Science Fiction Thriller
History Drama
Mystery Drama
Comedy Drama Family
Romance Comedy Crime Drama
Action Comedy Romance
Science Fiction Action Horror Thriller Adventure
Action Horror Science Fiction
Crime Action Mystery Thriller
Action Adventure Drama Romance Thriller
Family Fantasy Science Fiction Adventure
Action Adventure Comedy Crime Romance
Horror Thriller
Crime Drama Family
Crime Fantasy Drama
Comedy Crime Science Fiction
Animation Action Family Science Fiction
Drama Action Western
Action Drama Thriller War
Action Adventure Comedy Thriller Crime
Crime Drama Mystery Western
Action Comedy Drama
Action Adventure War
Fantasy Drama Crime
Mystery Thriller Drama
Adventure Animation Drama Family Music
Comedy Drama Romance Fantasy
Drama Crime Thriller
Action Fantasy Adventure
Drama Action Thriller
Crime Drama Thriller
Music Documentary
Drama Thriller Science Fiction
Comedy Adventure Crime
Thriller Science Fiction
Action Drama Thriller Crime
Family Comedy
Fantasy Action Science Fiction
Action Thriller Adventure Crime
Action Adventure Mystery Science Fiction Thriller
Thriller Action Comedy Science Fiction
Drama Comedy
Science Fiction Horror Action
Action Drama Mystery Thriller Crime
Drama Fantasy Comedy
Crime Drama Action Thriller
Comedy Adventure
Romance Comedy Crime
Comedy Drama Family Science Fiction
Science Fiction Animation Family Comedy Adventure
Crime Comedy Romance
Action Adventure Crime Drama Mystery
Action Science Fiction Fantasy Thriller Horror
Family Animation Adventure
Horror Science Fiction Mystery
Action Adventure Drama History Romance
Horror Science Fiction Thriller
Drama Fantasy Mystery Romance
Action Adventure Drama Mystery Romance
Comedy Science Fiction Adventure Family
Action Comedy Thriller Crime Science Fiction
Adventure Fantasy Action Drama
Drama Romance Adventure War
War Action
Adventure Horror Comedy
Science Fiction Comedy Family Romance
Action Adventure Thriller War
Comedy Western
Action Adventure Horror Science Fiction
Action Comedy Crime Drama
Action Comedy Drama Family Thriller
Adventure Drama Action Thriller
Comedy Music Family Fantasy Animation
Adventure Animation Drama Family
Adventure Comedy Family Romance
Thriller Action Crime
Thriller Drama Mystery
Drama Thriller Crime Mystery Romance
Adventure Action Comedy Western
Science Fiction Action Horror
History Drama Music
Action Thriller Crime Adventure
Animation Adventure Family Comedy
Action Drama Science Fiction Thriller
Thriller Drama Romance
Comedy Adventure Crime Family
Fantasy Horror Action Thriller
Action Adventure Crime Thriller
Mystery Thriller Crime
Crime Drama
War Drama History
Thriller Action Horror
Thriller Drama History
Action Comedy Fantasy
Science Fiction Thriller Romance
Thriller Science Fiction Mystery
Crime Comedy Action
Horror Romance
Fantasy Comedy Music
Action Adventure Drama Mystery Science Fiction
Drama Comedy Family
Action Thriller Mystery
Adventure Family Fantasy Science Fiction Thriller
Action Thriller Fantasy
Action Adventure Comedy Western
Comedy Family Adventure Fantasy Romance
Fantasy Horror Action
Thriller Drama
Action Drama History Thriller War
Romance Animation Adventure Comedy Family
Action Drama
Horror Mystery
Comedy Horror Fantasy
Horror Action Science Fiction
Drama Adventure Romance Thriller
Drama Fantasy
Action Adventure Romance Science Fiction Thriller
Adventure Comedy Drama
War Action Drama History Thriller
Action Crime Drama Mystery Thriller
Thriller Crime Mystery
Adventure Drama Action History War
Action Thriller Mystery Romance
Fantasy Drama Romance
Comedy Crime Drama Thriller
Comedy Drama Romance Science Fiction
Fantasy Thriller Action Crime
Action Comedy Thriller Crime Mystery
Crime Action Science Fiction
Drama Mystery Thriller Crime
Horror
Adventure Comedy
Comedy Fantasy Romance Science Fiction
Fantasy Comedy Romance
Music Drama Crime Romance
Western
Thriller Action
Comedy Drama Thriller
Drama Crime Romance
Drama Science Fiction Adventure Mystery
Animation Comedy Family Fantasy Science Fiction
Drama Horror Thriller Romance
Action Western Drama Fantasy Thriller
Drama Thriller Mystery War
Comedy Crime Action
Action Science Fiction Adventure Comedy Family
Comedy Drama Family Romance
Drama Thriller Crime Mystery
Comedy Family Music
Horror Action
Adventure Horror Thriller
Romance Comedy Family
Adventure Comedy Family Science Fiction
Adventure Action Comedy
Adventure Drama Music Romance
Action Adventure Crime Drama Thriller
Adventure Comedy Family Fantasy Science Fiction
Comedy Music
Drama Romance Western
Adventure Action Horror Science Fiction
Action Drama Fantasy
Crime Adventure Action Comedy Thriller
Adventure Action Thriller Crime Mystery
Action Drama History Western
Fantasy Action Science Fiction Thriller
Romance Comedy Drama
Drama Horror Mystery
Fantasy Thriller Horror
Drama Adventure Action History
Adventure Fantasy Action Western Thriller
Adventure Comedy Animation
Adventure Drama Romance Action
Thriller Fantasy Action Comedy
Action Adventure Comedy Family Science Fiction
Romance Horror
Drama Thriller History
Drama Romance Comedy
Comedy Adventure Fantasy Science Fiction Action
Action Adventure Fantasy Horror Science Fiction
Animation Comedy Adventure Family Science Fiction
Action Science Fiction Adventure Thriller
Comedy Crime Drama Romance Thriller
Fantasy Drama Comedy Family
Music Drama
Drama History Mystery
Fantasy Action Science Fiction Thriller Horror
Comedy Music Romance
Comedy Crime Romance
Crime Action Adventure
Drama Horror Thriller Crime
Fantasy Horror Science Fiction
Comedy War
Action Thriller Crime Drama
Fantasy Animation Drama Romance Family
Adventure Drama Romance
Drama Mystery
Action Horror Mystery Science Fiction Thriller
Adventure Fantasy Animation Comedy Science Fiction
Action Drama Crime
Adventure Action Family
Action Crime Thriller Drama
Action Adventure Thriller Drama
Action Drama History
Fantasy Action Thriller
Action Adventure War History
Drama Romance Fantasy
Comedy Action Adventure Fantasy Science Fiction
Action Adventure Family
Adventure Family Fantasy Animation
Action Comedy Family
Music Drama Comedy
Horror Mystery Science Fiction
Science Fiction Action Thriller
Action Adventure Mystery Thriller
Action Western
Adventure Action Comedy Romance
Drama Action
Drama Family
Action Fantasy Science Fiction Thriller
Science Fiction Comedy Adventure
Family Drama
Drama Thriller Horror
Thriller Science Fiction Mystery Romance
Adventure Comedy Crime Science Fiction
Action Comedy Family Adventure
Drama Adventure Western
Drama Romance War
Adventure Comedy Family
Fantasy Action Adventure Science Fiction Thriller
Comedy Crime Thriller
Adventure Comedy Fantasy
Drama Crime History
Drama Fantasy Horror
Action Thriller Crime Mystery
Crime Action Thriller
Crime History
Drama Mystery Science Fiction Thriller
Family Fantasy Comedy
Thriller Action Mystery
Horror Comedy
War Adventure Drama Romance
Action Horror Thriller
Action Adventure Drama History
Action Crime Mystery Thriller
Drama Fantasy Horror Mystery Romance
Adventure Drama Thriller
Fantasy Family Action
Thriller Crime Romance
Drama War Romance Western
Action Comedy Western Crime
Action Mystery Science Fiction Thriller
Drama Adventure Science Fiction Romance
Romance Drama Adventure
Crime Comedy
Family Fantasy Animation Adventure
Horror Action Thriller Science Fiction
Music Drama Romance
Action Crime Horror Thriller
Mystery Thriller
Drama Fantasy Romance Science Fiction
Fantasy Comedy Drama
Action Comedy Romance Thriller
Action Science Fiction Thriller Crime
Fantasy Drama Horror Action Thriller
Animation Comedy Family Music
War Crime Drama Mystery Romance
Music Drama Family
Action Adventure Thriller Science Fiction
Comedy Horror
Crime Drama Science Fiction Thriller
Comedy Thriller Crime
Action Comedy Crime Drama Music
Crime Comedy Adventure
Comedy Family Romance
Thriller Crime Drama Mystery
Comedy Drama Family Music Romance
Adventure Drama Romance War
Horror Comedy Romance
Fantasy Comedy Science Fiction Romance
Comedy Drama Family Fantasy
Romance Fantasy Animation Music
Adventure Comedy Crime
Horror Comedy Music
Action Fantasy Science Fiction
Drama Horror
Music
Action Adventure Crime Drama
Action Adventure Animation Science Fiction Thriller
Fantasy Drama Action Comedy Crime
Thriller Crime Horror
Romance Drama Thriller Crime
Action Drama Crime Thriller
Action Comedy Horror Thriller
Horror Thriller Science Fiction
Action Adventure Horror Thriller
Drama Mystery Romance Thriller
Action Adventure Fantasy Science Fiction Thriller
Adventure Fantasy Mystery
Thriller Action Crime Drama
Drama Family Romance
Fantasy Drama Action Thriller Romance
Action Drama Western
Fantasy Adventure Animation
Adventure Animation Comedy Fantasy
Drama Horror Comedy
Drama Mystery Thriller Fantasy
Animation Family Comedy Adventure Fantasy
Crime Mystery Thriller Action
Music Comedy Drama
Animation Science Fiction
Thriller Science Fiction Action Crime
Romance
Thriller Horror
Science Fiction Drama Thriller
Documentary
Comedy Drama Family Fantasy Romance
Romance Horror Comedy Thriller
Drama Adventure History
Music Comedy Action Crime
Adventure Comedy Drama Family
Horror Comedy Action Science Fiction Thriller
Drama Family Fantasy Adventure
Mystery Science Fiction
Crime Action Drama
Family Comedy Action
Thriller Action Comedy Crime
Comedy Drama Music
Romance History
Thriller Crime Action
Adventure Family Science Fiction Thriller
Action Crime Drama Western
Drama Thriller War
Drama Thriller Mystery Romance
Crime Thriller Mystery
Fantasy Horror
Comedy Crime Mystery Romance Thriller
Adventure Family
Science Fiction Mystery Thriller
Thriller Action Drama Music Romance
Mystery Fantasy Adventure Comedy
Thriller Adventure Mystery Fantasy

In [55]:
ORDER_OF_POPULARITY = df['popularity'].sort_values(ascending=False)
print(ORDER_OF_POPULARITY)

546     875.581305
95      724.247784
788     514.569956
94      481.098624
127     434.278564
           ...
4625      0.001389
4118      0.001186
4727      0.001117
3361      0.000372
4553      0.000000
Name: popularity, Length: 4803, dtype: float64

In [56]:
# for names in df["popularity"].unique().sort():
#   print(df["original_title"])

df_sorted = df.sort_values(by="popularity", ascending=False)

for title in df_sorted["original_title"]:
    print(title)

Minions
Interstellar
Deadpool
Guardians of the Galaxy
Mad Max: Fury Road
Jurassic World
Pirates of the Caribbean: The Curse of the Black Pearl
Dawn of the Planet of the Apes
The Hunger Games: Mockingjay - Part 1
Big Hero 6
Terminator Genisys
Captain America: Civil War
Whiplash
The Dark Knight
The Martian
Inception
Frozen
Batman v Superman: Dawn of Justice
Avatar
Fight Club
Pirates of the Caribbean: Dead Man's Chest
The Imitation Game
The Avengers
The Godfather
Teenage Mutant Ninja Turtles
Gone Girl
Pixels
Fury
X-Men: Apocalypse
Pirates of the Caribbean: At World's End
Rise of the Planet of the Apes
Forrest Gump
The Lord of the Rings: The Fellowship of the Ring
Despicable Me 2
The Shawshank Redemption
Pirates of the Caribbean: On Stranger Tides
Avengers: Age of Ultron
Harry Potter and the Chamber of Secrets
The Maze Runner
Tomorrowland
Inside Out
One Flew Over the Cuckoo's Nest
The Hunger Games: Mockingjay - Part 2
Twilight
Star Wars
Brave
The Lord of the Rings: The Return of the King
Pulp Fiction
The Hobbit: The Battle of the Five Armies
Iron Man
Ant-Man
千と千尋の神隠し
X-Men: Days of Future Past
Transformers: Age of Extinction
Chappie
Spider-Man 3
Night at the Museum: Secret of the Tomb
Lucy
Batman Begins
Mission: Impossible - Rogue Nation
Despicable Me
Maze Runner: The Scorch Trials
The Dark Knight Rises
Maleficent
Gravity
Harry Potter and the Philosopher's Stone
Bruce Almighty
The Fifth Element
The Hobbit: An Unexpected Journey
Quantum of Solace
Spectre
The Twilight Saga: Eclipse
The Lord of the Rings: The Two Towers
Monsters, Inc.
The Godfather: Part II
Schindler's List
The Matrix
Men in Black
Insurgent
The Green Mile
Furious 7
Terminator 2: Judgment Day
Exodus: Gods and Kings
Harry Potter and the Goblet of Fire
Cinderella
It Follows
The Revenant
San Andreas
We're the Millers
How to Train Your Dragon 2
Titanic
The Twilight Saga: Breaking Dawn - Part 2
Ice Age
Thor: The Dark World
Man of Steel
Harry Potter and the Half-Blood Prince
Fifty Shades of Grey
12 Years a Slave
I, Robot
Gladiator
Ex Machina
The Wolf of Wall Street
The Twilight Saga: New Moon
The Hobbit: The Desolation of Smaug
The Jungle Book
Alien
Blade Runner
Psycho
Skyfall
Aladdin
Up
Men in Black II
Black Swan
El laberinto del fauno
The Lion King
The Bourne Legacy
Suicide Squad
The Adventures of Tintin
The Amazing Spider-Man
Birdman
The Amazing Spider-Man 2
Monsters University
Nightcrawler
Casino Royale
Taken 3
Prisoners
Il buono, il brutto, il cattivo
American Sniper
A Bug's Life
Thor
The Bourne Identity
2001: A Space Odyssey
Allegiant
Finding Nemo
Sin City: A Dame to Kill For
Jupiter Ascending
The Mask
Ice Age: The Meltdown
Kung Fu Panda
V for Vendetta
Penguins of Madagascar
The Devil Wears Prada
Non-Stop
The Purge: Anarchy
Cars
Spider-Man
The Hangover
Horrible Bosses 2
Django Unchained
The Age of Adaline
Shutter Island
World War Z
Underworld
Night at the Museum: Battle of the Smithsonian
Sherlock Holmes: A Game of Shadows
Home Alone 2: Lost in New York
Indiana Jones and the Last Crusade
Taken
American Beauty
The Pursuit of Happyness
Divergent
Snow White and the Seven Dwarfs
The Equalizer
Kill Bill: Vol. 1
Harry Potter and the Prisoner of Azkaban
Se7en
Edge of Tomorrow
The Shining
Alice in Wonderland
The Empire Strikes Back
Star Trek Into Darkness
Harry Potter and the Order of the Phoenix
The Incredibles
Mission: Impossible - Ghost Protocol
Iron Man 3
The Expendables
Iron Man 2
Snow White and the Huntsman
Hercules
Ocean's Twelve
Back to the Future
The Hunger Games: Catching Fire
Saving Private Ryan
Indiana Jones and the Kingdom of the Crystal Skull
Mission: Impossible
About Time
Run All Night
Captain America: The First Avenger
The Prestige
The Grand Budapest Hotel
The Fault in Our Stars
The Terminator
The Interview
The Cabin in the Woods
Catch Me If You Can
Cloud Atlas
Wanted
TRON: Legacy
Le fabuleux destin d'Amélie Poulain
Toy Story
Star Trek
Toy Story 2
American History X
The Matrix Revolutions
The Butterfly Effect
The Sixth Sense
Trainwreck
Sex Tape
Inglourious Basterds
Captain America: The Winter Soldier
Rocky
Terminator Salvation
300: Rise of an Empire
Pitch Perfect 2
Now You See Me
I Am Legend
The Matrix Reloaded
Let's Be Cops
Million Dollar Baby
Gattaca
Scarface
Ice Age: Dawn of the Dinosaurs
Terminator 3: Rise of the Machines
The Social Network
Prometheus
Ted
The Conjuring 2
Megamind
Ted 2
The Hateful Eight
The Hunger Games
Raiders of the Lost Ark
Apollo 13
Dumb and Dumber To
Oblivion
Aliens
Grease
Angels & Demons
Mulan
The Wizard of Oz
The Chronicles of Narnia: The Lion, the Witch and the Wardrobe
Elysium
Shrek
How to Train Your Dragon
Blade II
Indiana Jones and the Temple of Doom
Reservoir Dogs
Troy
RoboCop
WALL·E
Sausage Party
Ghostbusters
Die Hard
Room
Self/less
Sin City
Minority Report
Into the Woods
Ratatouille
A Good Day to Die Hard
Southpaw
Star Trek Beyond
Ice Age: Continental Drift
300
Battleship
Watchmen
Monty Python and the Holy Grail
Paper Towns
Chronicle
Dracula Untold
Snowpiercer
The Croods
From Dusk Till Dawn
The Usual Suspects
Carrie
Saw
GoodFellas
Seventh Son
Silver Linings Playbook
Trainspotting
Home
The Departed
Warcraft
District 9
Mission: Impossible III
First Blood
Nerve
The Game
The Incredible Hulk
The Italian Job
21 Jump Street
Jason Bourne
Spring Breakers
The Princess and the Frog
Wreck-It Ralph
Prince of Persia: The Sands of Time
Argo
London Has Fallen
Rise of the Guardians
Straight Outta Compton
Hotel Transylvania 2
50 First Dates
A Walk Among the Tombstones
The Iron Giant
King Kong
Donnie Darko
The Great Gatsby
The Theory of Everything
Percy Jackson & the Olympians: The Lightning Thief
The Expendables 3
Ocean's Eleven
The Shallows
4: Rise of the Silver Surfer
American Pie
もののけ姫
Braveheart
Memento
The Huntsman: Winter's War
Independence Day
The Curious Case of Benjamin Button
Everest
In Time
Annabelle
The Mummy: Tomb of the Dragon Emperor
Toy Story 3
Mary Poppins
GoldenEye
Focus
The Lego Movie
Dallas Buyers Club
Olympus Has Fallen
G.I. Joe: Retaliation
12 Angry Men
Slumdog Millionaire
A Beautiful Mind
Source Code
The Godfather: Part III
Batman Returns
Transcendence
Top Gun
National Treasure
Taxi Driver
Starship Troopers
Insidious
Hellboy II: The Golden Army
Beetlejuice
Armageddon
Underworld: Awakening
The Hangover Part II
Superman Returns
The 5th Wave
The Book Thief
Sherlock Holmes
Creed
The Terminal
Cast Away
Die Hard 2
Dredd
The Big Short
Moulin Rouge!
Zombieland
There's Something About Mary
Jack Reacher
Lara Croft Tomb Raider: The Cradle of Life
Dirty Grandpa
올드보이
Hancock
Kung Fu Panda 3
Pacific Rim
The Truman Show
Eternal Sunshine of the Spotless Mind
Ouija
Alice Through the Looking Glass
Hotel Transylvania
Gods of Egypt
E.T. the Extra-Terrestrial
The World's End
9
Lilo & Stitch
Dead Poets Society
Sicario
Contact
The Notebook
Mission: Impossible II
The Fugitive
Need for Speed
10 Things I Hate About You
The Purge
Die Another Day
The King's Speech
Star Wars: Episode I - The Phantom Menace
The Chronicles of Narnia: Prince Caspian
Charlie and the Chocolate Factory
The Giver
The Expendables 2
The Purge: Election Year
10 Cloverfield Lane
Her
Steve Jobs
No Country for Old Men
Snatch
The Bourne Supremacy
Me Before You
The Intern
Journey to the Center of the Earth
Panic Room
Hansel & Gretel: Witch Hunters
Gone in Sixty Seconds
Blood Diamond
Captain Phillips
Groundhog Day
The Thing
The Last Witch Hunter
17 Again
127 Hours
Close Encounters of the Third Kind
Mortdecai
22 Jump Street
The Last Samurai
Training Day
Men in Black 3
Zodiac
Underworld: Rise of the Lycans
Warrior
Die Hard: With a Vengeance
Green Lantern
The Hitchhiker's Guide to the Galaxy
The Good Dinosaur
Atlantis: The Lost Empire
Now You See Me 2
Sunshine
The Rock
Life of Pi
Kung Fu Panda 2
Planet of the Apes
Coraline
The Emperor's New Groove
Stand by Me
In the Heart of the Sea
Gran Torino
Forgetting Sarah Marshall
Kill Bill: Vol. 2
The Pianist
Pompeii
The Witch
Horrible Bosses
Dark Shadows
Neighbors 2: Sorority Rising
Interview with the Vampire
Jaws
Batman & Robin
Predator
Cars 2
The Conjuring
Apocalypse Now
Autómata
Platoon
American Hustle
The Chronicles of Narnia: The Voyage of the Dawn Treader
Blade: Trinity
Law Abiding Citizen
ハウルの動く城
Speed
End of Watch
Rain Man
Taken 2
Once Upon a Time in America
C'era una volta il West
Drive
True Grit
The Big Lebowski
Battle: Los Angeles
Shaun of the Dead
Road to Perdition
Project X
The Lone Ranger
Underworld: Evolution
Gone with the Wind
Live Free or Die Hard
Dr. No
Salt
3:10 to Yuma
Before I Go to Sleep
Night at the Museum
Independence Day: Resurgence
The Man from U.N.C.L.E.
Tangled
Ghost Rider: Spirit of Vengeance
War of the Worlds
The Grey
Superman
Bridge of Spies
Insidious: Chapter 2
Les Misérables
Side Effects
Batman Forever
Lights Out
Mirror Mirror
Madagascar
Pan
Wild Card
Stardust
Crank
Chicken Little
The Neverending Story
Pocahontas
Goldfinger
Vacation
Clash of the Titans
Bambi
The Girl with the Dragon Tattoo
Predators
The Exorcist
Transporter 2
Lo imposible
Edward Scissorhands
Hellboy
Paranormal Activity
Mama
The League of Extraordinary Gentlemen
Alvin and the Chipmunks
The Polar Express
Shrek 2
Shark Tale
The Hurt Locker
Oz: The Great and Powerful
Cloverfield
Eagle Eye
The Simpsons Movie
Ghost Rider
Blackhat
Cloudy with a Chance of Meatballs
The Hunchback of Notre Dame
Riddick
Return of the Jedi
Looper
xXx
The Hunt for Red October
Rio
Big Fish
Moneyball
Gangs of New York
Airplane!
Noah
Moon
How to Be Single
Face/Off
Black Mass
Pinocchio
Scream
Ender's Game
Insidious: Chapter 3
Identity
Alien³
Back to the Future Part III
卧虎藏龙
Inherent Vice
The Angry Birds Movie
Dances with Wolves
Lost in Translation
The Aviator
(500) Days of Summer
Grown Ups 2
Anastasia
The Mortal Instruments: City of Bones
28 Days Later
Step Up
Pretty Woman
How the Grinch Stole Christmas
Easy A
Serenity
The Bourne Ultimatum
Goosebumps
Central Intelligence
The November Man
The Da Vinci Code
American Psycho
Man on Fire
2012
Inside Man
Con Air
Red Riding Hood
21
Drag Me to Hell
Gremlins
Kick-Ass
Dracula
Madagascar 3: Europe's Most Wanted
The Holiday
Wrath of the Titans
Knight and Day
Collateral
Turbo
The Blues Brothers
The Crow
Cube
Waterworld
Mr. & Mrs. Smith
Equilibrium
The Princess Bride
Dawn of the Dead
Fear and Loathing in Las Vegas
Kingdom of Heaven
Escape Plan
Black Hawk Down
Cidade de Deus
RED 2
Philadelphia
The BFG
Madagascar: Escape 2 Africa
Brokeback Mountain
Blended
Star Wars: Episode III - Revenge of the Sith
Batman
The Mechanic
Mars Attacks!
Shrek Forever After
Star Wars: Episode II - Attack of the Clones
John Carter
The Last Stand
The Monuments Men
Due Date
The Tree of Life
Yes Man
Blade
St. Vincent
Midnight in Paris
Warm Bodies
Good Will Hunting
Casablanca
The Woman in Black
Into the Wild
Corpse Bride
I Am Number Four
The Perks of Being a Wallflower
Boyhood
Jack the Giant Slayer
The Secret Life of Walter Mitty
Back to the Future Part II
Hachi: A Dog's Tale
Tropic Thunder
Paul
Total Recall
School of Rock
Unbroken
The Golden Compass
Shrek the Third
AVP: Alien vs. Predator
Wild
The Host
Tomorrow Never Dies
2 Guns
It's a Wonderful Life
After Earth
The Legend of Tarzan
Hitman
Death Race
Perfume: The Story of a Murderer
Jack Ryan: Shadow Recruit
13 Hours: The Secret Soldiers of Benghazi
Bad Moms
The Judge
Rio 2
American Gangster
Flight
The Help
Saw II
Ocean's Thirteen
Unbreakable
Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb
Unfriended
Ghost
The Longest Ride
The Day the Earth Stood Still
The Mummy Returns
Bolt
Pineapple Express
47 Ronin
The Blair Witch Project
Spirit: Stallion of the Cimarron
3 Days to Kill
Apocalypto
13 Going on 30
Antz
Spotlight
Lara Croft: Tomb Raider
Romeo + Juliet
Seven Pounds
RED
The Tourist
The Day After Tomorrow
The Beach
Insomnia
From Russia with Love
Lawrence of Arabia
Enemy at the Gates
Fantastic Mr. Fox
Paul Blart: Mall Cop 2
Ace Ventura: Pet Detective
Cloudy with a Chance of Meatballs 2
Enemy of the State
Click
DodgeBall: A True Underdog Story
Brazil
Moonrise Kingdom
The Road
Sinister
The Descendants
Wild Wild West
Journey 2: The Mysterious Island
Beautiful Creatures
Resident Evil
Shame
Bridge to Terabithia
Jackie Brown
The Taking of Pelham 1 2 3
You Don't Mess with the Zohan
Friends with Benefits
Jurassic Park
A Few Good Men
Child 44
Donnie Brasco
The DUFF
Kick-Ass 2
Serbuan maut
Percy Jackson: Sea of Monsters
Charlie's Angels
The Wrestler
The Princess Diaries
The Brothers Grimm
Austin Powers in Goldmember
The Thin Red Line
Casino
Maggie
American Reunion
Spaceballs
Paddington
Teenage Mutant Ninja Turtles: Out of the Shadows
The Girl Next Door
七人の侍
A Christmas Carol
O Brother, Where Art Thou?
The World Is Not Enough
崖の上のポニョ
ParaNorman
R.I.P.D.
The Watch
Aliens vs Predator: Requiem
アキラ
Brooklyn
Dark City
Some Like It Hot
Sucker Punch
Alexander
Hail, Caesar!
White House Down
Me, Myself & Irene
This Means War
The Visit
Treasure Planet
Scott Pilgrim vs. the World
Grown Ups
Valkyrie
Hostel
Contagion
Trance
Final Destination
Per un pugno di dollari
Mr. Peabody & Sherman
True Lies
No Strings Attached
Rambo: First Blood Part II
Unknown
Abraham Lincoln: Vampire Hunter
We Bought a Zoo
Hot Fuzz
Daddy's Home
Final Destination 5
The 40 Year Old Virgin
This Is 40
Zero Dark Thirty
Money Monster
The Untouchables
This Is the End
A Nightmare on Elm Street
The Boy
The Passion of the Christ
The Neon Demon
Fantastic Four
Anchorman 2: The Legend Continues
What Happens in Vegas
Zoolander
Bad Boys II
Date Night
Phone Booth
No Escape
Crazy, Stupid, Love.
The Sound of Music
Immortals
As Good as It Gets
That Awkward Moment
There Will Be Blood
The Last of the Mohicans
Safe Haven
Unstoppable
The Island
Robin Hood
The Heat
A Most Violent Year
I Origins
The Scorpion King
Body of Lies
The Time Traveler's Wife
Alien: Resurrection
Unforgiven
Shooter
Final Destination 2
The Walk
Legend of the Guardians: The Owls of Ga'Hoole
Happy Feet
Zoolander 2
Real Steel
The Imaginarium of Doctor Parnassus
The Addams Family
Mad Max 2
The Mist
Lone Survivor
Love Actually
Super 8
The Road to El Dorado
Just Go with It
Master and Commander: The Far Side of the World
The Illusionist
The SpongeBob Movie: Sponge Out of Water
Lucky Number Slevin
Scary Movie 5
Swordfish
Remember Me
Tower Heist
Epic
xXx: State of the Union
A Knight's Tale
Surrogates
The Smurfs
The Three Musketeers
Scary Movie 3
Pride & Prejudice
Mad Max Beyond Thunderdome
Singin' in the Rain
Neighbors
Young Frankenstein
American Pie 2
Mean Girls
Air Force One
Monster House
Over the Hedge
Inside Llewyn Davis
Lincoln
Get Hard
The Proposal
Poltergeist
American Wedding
Melancholia
Lethal Weapon 3
Monsters vs Aliens
Austin Powers: International Man of Mystery
Saw 3D
Space Jam
Meet Joe Black
Magic Mike
Annie Hall
Oculus
Rush Hour 2
Dumb and Dumber
Only God Forgives
Homefront
Begin Again
The Grudge
Evil Dead II
Johnny English Reborn
Beowulf
The Sorcerer's Apprentice
Walk the Line
Crank: High Voltage
Patch Adams
The Assassination of Jesse James by the Coward Robert Ford
Raging Bull
21 & Over
Eastern Promises
The Pacifier
The Place Beyond the Pines
Children of Men
The Little Prince
Scary Movie 2
Movie 43
Bridget Jones's Diary
Still Alice
True Romance
The Machinist
Scream 2
Lockout
Gandhi
Scream 4
1408
Spider-Man 2
Concussion
National Lampoon’s Van Wilder
The Hills Have Eyes
The Punisher
The Great Escape
The Evil Dead
The Counselor
Hulk
Three Kings
Das Leben der Anderen
The Boondock Saints
The Book of Life
Big Daddy
Lord of War
The Boy in the Striped Pyjamas
Safe House
28 Weeks Later
Blue Jasmine
Diamonds Are Forever
A History of Violence
Hitch
The Call
The Other Woman
The Transporter
The Next Three Days
Ace Ventura: When Nature Calls
Babe
The Peanuts Movie
Commando
Pearl Harbor
Finding Neverland
Deep Impact
S.W.A.T.
Man on a Ledge
A.I. Artificial Intelligence
Trading Places
Identity Thief
Gremlins 2: The New Batch
The Best of Me
Hot Tub Time Machine
The Reader
Evil Dead
The Bone Collector
Bad Boys
The Devil's Advocate
Colombiana
The Last Airbender
Army of Darkness
The Bounty Hunter
Up in the Air
Public Enemies
Tinker Tailor Soldier Spy
Hook
Survivor
Charlie's Angels: Full Throttle
Wrong Turn
Point Break
Left Behind
Annie
Superbad
30 Days of Night
Bride Wars
50/50
Atonement
Don Jon
A Walk to Remember
What's Eating Gilbert Grape
Along Came Polly
Mad Max
Saw III
Rush
Saw V
Project Almanac
Silent Hill
Secret Window
Fantasia
Legend
G.I. Joe: The Rise of Cobra
Buried
Mr. Popper's Penguins
Meet the Fockers
A Million Ways to Die in the West
8 Mile
Vicky Cristina Barcelona
Pitch Perfect
Midnight Special
Knowing
Kiss Kiss Bang Bang
Ronin
Miss Congeniality
The Exorcism of Emily Rose
Tremors
Scary Movie 4
La grande bellezza
The Final Destination
Irréversible
The Smurfs 2
Der Untergang
Little Fockers
The Book of Eli
Metropolis
Hugo
16 Blocks
Seven Psychopaths
Catwoman
Stranger Than Fiction
Jennifer's Body
21 Grams
The Ring Two
Jarhead
Chicago
The Way Way Back
The Butler
Twister
Flightplan
Last Action Hero
The Change-Up
Pete's Dragon
Saving Mr. Banks
Burn After Reading
Safe
Saw VI
Pain & Gain
RockNRolla
42
Savages
Amadeus
Conan the Barbarian
Shakespeare in Love
DragonHeart
Chicken Run
LOL
Wild Hogs
The Green Hornet
[REC]
Disturbia
Final Destination 3
Mulholland Drive
Where the Wild Things Are
Krampus
The Secret Life of Pets
Scooby-Doo
What Women Want
The Talented Mr. Ripley
Contraband
The Dictator
The Man from Earth
I, Frankenstein
The Bucket List
Rambo III
Paul Blart: Mall Cop
Mystic River
Hanna
If I Stay
Hairspray
The Mask of Zorro
Extremely Loud & Incredibly Close
The Legend of Zorro
Thunderball
The Boat That Rocked
The Fighter
Magnolia
Never Let Me Go
Legion
Attack the Block
Marley & Me
Devil
K-PAX
Milk
Mrs. Doubtfire
Eragon
Seeking a Friend for the End of the World
Galaxy Quest
Mamma Mia!
27 Dresses
Match Point
The Boxtrolls
Garden State
Snitch
Tombstone
Superman II
Burnt
Stuart Little
Live and Let Die
Rocky Balboa
Outbreak
The Bank Job
Drive Angry
The Curse of the Were-Rabbit
The Ninth Gate
Erin Brockovich
Halloween
The Elephant Man
Green Zone
The Man with the Golden Gun
The Amityville Horror
25th Hour
The Running Man
Delivery Man
La migliore offerta
The Princess Diaries 2: Royal Engagement
Green Room
Meet the Parents
Æon Flux
The Artist
Rango
Moonraker
The Lake House
Resident Evil: Apocalypse
Joy
Shallow Hal
They Live
Beverly Hills Cop
Four Weddings and a Funeral
Big Trouble in Little China
Event Horizon
Under the Skin
Step Up Revolution
Dope
Magic Mike XXL
Aloha
Dead Man Down
Ben-Hur
Robots
Barry Lyndon
August Rush
War Horse
Killer Elite
Death Becomes Her
Broken City
P.S. I Love You
Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan
The Prince of Egypt
Analyze This
Alvin and the Chipmunks: The Squeakquel
The English Patient
Triple 9
Eddie the Eagle
Deliver Us from Evil
Anchorman: The Legend of Ron Burgundy
Bee Movie
Orphan
The Texas Chain Saw Massacre
Doom
The Lovely Bones
Highlander
Saw IV
Out of the Furnace
Nebraska
Enchanted
The Core
Definitely, Maybe
Paranormal Activity 3
The Skeleton Key
Machete Kills
El orfanato
Gangster Squad
Munich
Selma
Philomena
Paycheck
Thank You for Smoking
The Man in the Iron Mask
Step Up 2: The Streets
Notting Hill
The Flintstones
The Crazies
Κυνόδοντας
Starsky & Hutch
Signs
Australia
We Are Your Friends
Bridget Jones: The Edge of Reason
Robin Hood: Prince of Thieves
Eat Pray Love
Chocolat
The Negotiator
White Chicks
You Only Live Twice
Parker
The Land Before Time
The Naked Gun 33⅓: The Final Insult
Elektra
Hotel Rwanda
Big Eyes
All Is Lost
You've Got Mail
Transformers: Dark of the Moon
The Sting
Bad Teacher
Ride Along
The Karate Kid
Pride and Prejudice and Zombies
Pandorum
Priest
Blow
Modern Times
About a Boy
The Finest Hours
Crash
Licence to Kill
Hollow Man
J. Edgar
The Frozen Ground
Last Vegas
Johnny English
Daybreakers
Stuart Little 2
Idiocracy
Predator 2
From Paris with Love
Frankenweenie
Sabotage
The Hundred-Foot Journey
Criminal
The SpongeBob SquarePants Movie
Eyes Wide Shut
Alvin and the Chipmunks: The Road Chip
The Chronicles of Riddick
Pi
Ghost Ship
Cape Fear
The Five-Year Engagement
Anaconda
Mr. Bean's Holiday
The Signal

In [57]:
df.head(547)

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,cast,crew,director
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,Sam Worthington Zoe Saldana Sigourney Weaver S...,"[{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...",James Cameron
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,Johnny Depp Orlando Bloom Keira Knightley Stel...,"[{'name': 'Dariusz Wolski', 'gender': 2, 'depa...",Gore Verbinski
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,Daniel Craig Christoph Waltz L\u00e9a Seydoux ...,"[{'name': 'Thomas Newman', 'gender': 2, 'depar...",Sam Mendes
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Christian Bale Michael Caine Gary Oldman Anne ...,"[{'name': 'Hans Zimmer', 'gender': 2, 'departm...",Christopher Nolan
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,Taylor Kitsch Lynn Collins Samantha Morton Wil...,"[{'name': 'Andrew Stanton', 'gender': 2, 'depa...",Andrew Stanton
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
542,542,0,Action Drama Horror Science Fiction Thriller,NaN,25769,beach desperation infection survival biohazard,en,Carriers,Four friends fleeing a viral pandemic soon lea...,12.708963,...,84.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"The rules are simple. You break them, you die...",Carriers,5.8,282,Lou Taylor Pucci Chris Pine Piper Perabo Emily...,"[{'name': 'Anthony Bregman', 'gender': 2, 'dep...",\u00c0lex Pastor
543,543,75000000,Adventure Fantasy Animation Action Comedy,NaN,23685,parallel world organ donation horniness agent ...,en,Monkeybone,After a car crash sends repressed cartoonist S...,8.098369,...,93.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"If It Yells, If It Swings, It's Got To Be Monk...",Monkeybone,4.3,78,Brendan Fraser Bridget Fonda John Turturro Chr...,"[{'name': 'Anne Dudley', 'gender': 1, 'departm...",Henry Selick
544,544,45000000,Action Adventure Drama Thriller,NaN,11866,robbery water gobi desert disaster airplane crash,en,Flight of the Phoenix,When an Amacor oil rig in the Gobi Desert of M...,20.374308,...,113.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Out of the ashes, hope will rise.",Flight of the Phoenix,5.7,276,Dennis Quaid Tyrese Gibson Giovanni Ribisi Mir...,"[{'name': 'Bill Abbott', 'gender': 2, 'departm...",John Moore
545,545,75000000,Science Fiction Thriller Drama,NaN,9741,father son relationship train accident comic b...,en,Unbreakable,An ordinary man makes an extraordinary discove...,42.006908,...,106.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Some things are only revealed by accident.,Unbreakable,6.9,1946,Bruce Willis Samuel L. Jackson Robin Wright Sp...,"[{'name': 'Sam Mercer', 'gender': 2, 'departme...",M. Night Shyamalan
546,546,74000000,Family Animation Adventure Comedy,http://www.minionsmovie.com/,211672,assistant aftercreditsstinger duringcreditssti...,en,Minions,"Minions Stuart, Kevin and Bob are recruited by...",875.581305,...,91.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Before Gru, they had a history of bad bosses",Minions,6.4,4571,Sandra Bullock Jon Hamm Michael Keaton Allison...,"[{'name': 'Christopher Meledandri', 'gender': ...",Kyle Balda

In [58]:
# Selecting only the relevant features for recommendation
selected_features = ["genres", "keywords", "tagline", "cast", "director"]

In [59]:
# Replacing the null values in selected features column with null string
for feature in selected_features:
  df[feature] = df[feature].fillna("")

In [60]:
# Combining all the selected features
combined_features = df["genres"] + " " + df["keywords"] + " " + df["tagline"] + " " + df["cast"] + " " + df["director"]

In [61]:
print(combined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai Daniel Henney Eliza...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object

In [62]:
# Converting the text data into numerical values
vectorizer = TfidfVectorizer()

In [63]:
feature_vectors = vectorizer.fit_transform(combined_features)

In [64]:
print(feature_vectors)

  (0, 2432)	0.17272411194153
  (0, 7755)	0.1128035714854756
  (0, 13024)	0.1942362060108871
  (0, 10229)	0.16058685400095302
  (0, 8756)	0.22709015857011816
  (0, 14608)	0.15150672398763912
  (0, 16668)	0.19843263965100372
  (0, 14064)	0.20596090415084142
  (0, 13319)	0.2177470539412484
  (0, 17290)	0.20197912553916567
  (0, 17007)	0.23643326319898797
  (0, 13349)	0.15021264094167086
  (0, 11503)	0.27211310056983656
  (0, 11192)	0.09049319826481456
  (0, 16998)	0.1282126322850579
  (0, 15261)	0.07095833561276566
  (0, 4945)	0.24025852494110758
  (0, 14271)	0.21392179219912877
  (0, 3225)	0.24960162956997736
  (0, 16587)	0.12549432354918996
  (0, 14378)	0.33962752210959823
  (0, 5836)	0.1646750903586285
  (0, 3065)	0.22208377802661425
  (0, 3678)	0.21392179219912877
  (0, 5437)	0.1036413987316636
  :	:
  (4801, 17266)	0.2886098184932947
  (4801, 4835)	0.24713765026963996
  (4801, 403)	0.17727585190343226
  (4801, 6935)	0.2886098184932947
  (4801, 11663)	0.21557500762727902
  (4801, 1672)	0.1564793427630879
  (4801, 10929)	0.13504166990041588
  (4801, 7474)	0.11307961713172225
  (4801, 3796)	0.3342808988877418
  (4802, 6996)	0.5700048226105303
  (4802, 5367)	0.22969114490410403
  (4802, 3654)	0.262512960498006
  (4802, 2425)	0.24002350969074696
  (4802, 4608)	0.24002350969074696
  (4802, 6417)	0.21753405888348784
  (4802, 4371)	0.1538239182675544
  (4802, 12989)	0.1696476532191718
  (4802, 1316)	0.1960747079005741
  (4802, 4528)	0.19504460807622875
  (4802, 3436)	0.21753405888348784
  (4802, 6155)	0.18056463596934083
  (4802, 4980)	0.16078053641367315
  (4802, 2129)	0.3099656128577656
  (4802, 4518)	0.16784466610624255
  (4802, 11161)	0.17867407682173203

**USING COSINE SIMILARITY**

In [65]:
# Getting the similarity score using cosine similarity
similarity = cosine_similarity(feature_vectors)

In [66]:
print(similarity)

[[1.         0.07219487 0.037733   ... 0.         0.         0.        ]
 [0.07219487 1.         0.03281499 ... 0.03575545 0.         0.        ]
 [0.037733   0.03281499 1.         ... 0.         0.05389661 0.        ]
 ...
 [0.         0.03575545 0.         ... 1.         0.         0.02651502]
 [0.         0.         0.05389661 ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.02651502 0.         1.        ]]

In [67]:
# Taking the input name of movie from the user
movie_name = input("Enter the name of your favourite movie: ")

print("My favourite movie is :", movie_name)

Enter the name of your favourite movie: Titanic
My favourite movie is : Titanic

In [68]:
# Creating a list with all movie names given in the dataset
all_movie_names = df["title"].tolist()
print(all_movie_names)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lantern', 'Toy Story 3', 'Terminator Salvation', 'Furious 7', 'World War Z', 'X-Men: Days of Future Past', 'Star Trek Into Darkness', 'Jack the Giant Slayer', 'The Great Gatsby', 'Prince of Persia: The Sands of Time', 'Pacific Rim', 'Transformers: Dark of the Moon', 'Indiana Jones and the Kingdom of the Crystal Skull', 'The Good Dinosaur', 'Brave', 'Star Trek Beyond', 'WALL·E', 'Rush Hour 3', '2012', 'A Christmas Carol', 'Jupiter Ascending', 'The Legend of Tarzan', 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 'X-Men: Apocalypse', 'The Dark Knight', 'Up', 'Monsters vs Aliens', 'Iron Man', 'Hugo', 'Wild Wild West', 'The Mummy: Tomb of the Dragon Emperor', 'Suicide Squad', 'Evan Almighty', 'Edge of Tomorrow', 'Waterworld', 'G.I. Joe: The Rise of Cobra', 'Inside Out', 'The Jungle Book', 'Iron Man 2', 'Snow White and the Huntsman', 'Maleficent', 'Dawn of the Planet of the Apes', 'The Lovers', '47 Ronin', 'Captain America: The Winter Soldier', 'Shrek Forever After', 'Tomorrowland', 'Big Hero 6', 'Wreck-It Ralph', 'The Polar Express', 'Independence Day: Resurgence', 'How to Train Your Dragon', 'Terminator 3: Rise of the Machines', 'Guardians of the Galaxy', 'Interstellar', 'Inception', 'Shin Godzilla', 'The Hobbit: An Unexpected Journey', 'The Fast and the Furious', 'The Curious Case of Benjamin Button', 'X-Men: First Class', 'The Hunger Games: Mockingjay - Part 2', "The Sorcerer's Apprentice", 'Poseidon', 'Alice Through the Looking Glass', 'Shrek the Third', 'Warcraft', 'Terminator Genisys', 'The Chronicles of Narnia: The Voyage of the Dawn Treader', 'Pearl Harbor', 'Transformers', 'Alexander', 'Harry Potter and the Order of the Phoenix', 'Harry Potter and the Goblet of Fire', 'Hancock', 'I Am Legend', 'Charlie and the Chocolate Factory', 'Ratatouille', 'Batman Begins', 'Madagascar: Escape 2 Africa', 'Night at the Museum: Battle of the Smithsonian', 'X-Men Origins: Wolverine', 'The Matrix Revolutions', 'Frozen', 'The Matrix Reloaded', 'Thor: The Dark World', 'Mad Max: Fury Road', 'Angels & Demons', 'Thor', 'Bolt', 'G-Force', 'Wrath of the Titans', 'Dark Shadows', 'Mission: Impossible - Rogue Nation', 'The Wolfman', 'Bee Movie', 'Kung Fu Panda 2', 'The Last Airbender', 'Mission: Impossible III', 'White House Down', 'Mars Needs Moms', 'Flushed Away', 'Pan', 'Mr. Peabody & Sherman', 'Troy', "Madagascar 3: Europe's Most Wanted", 'Die Another Day', 'Ghostbusters', 'Armageddon', 'Men in Black II', 'Beowulf', 'Kung Fu Panda 3', 'Mission: Impossible - Ghost Protocol', 'Rise of the Guardians', 'Fun with Dick and Jane', 'The Last Samurai', 'Exodus: Gods and Kings', 'Star Trek', 'Spider-Man', 'How to Train Your Dragon 2', 'Gods of Egypt', 'Stealth', 'Watchmen', 'Lethal Weapon 4', 'Hulk', 'G.I. Joe: Retaliation', 'Sahara', 'Final Fantasy: The Spirits Within', 'Captain America: The First Avenger', 'The World Is Not Enough', 'Master and Commander: The Far Side of the World', 'The Twilight Saga: Breaking Dawn - Part 2', 'Happy Feet Two', 'The Incredible Hulk', 'The BFG', 'The Revenant', 'Turbo', 'Rango', 'Penguins of Madagascar', 'The Bourne Ultimatum', 'Kung Fu Panda', 'Ant-Man', 'The Hunger Games: Catching Fire', 'Home', 'War of the Worlds', 'Bad Boys II', 'Puss in Boots', 'Salt', 'Noah', 'The Adventures of Tintin', 'Harry Potter and the Prisoner of Azkaban', 'Australia', 'After Earth', 'Dinosaur', 'Night at the Museum: Secret of the Tomb', 'Megamind', "Harry Potter and the Philosopher's Stone", 'R.I.P.D.', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'The Hunger Games: Mockingjay - Part 1', 'The Da Vinci Code', 'Rio 2', 'X2', 'Fast Five', 'Sherlock Holmes: A Game of Shadows', 'Clash of the Titans', 'Total Recall', 'The 13th Warrior', 'The Bourne Legacy', 'Batman & Robin', 'How the Grinch Stole Christmas', 'The Day After Tomorrow', 'Mission: Impossible II', 'The Perfect Storm', 'Fantastic 4: Rise of the Silver Surfer', 'Life of Pi', 'Ghost Rider', 'Jason Bourne', "Charlie's Angels: Full Throttle", 'Prometheus', 'Stuart Little 2', 'Elysium', 'The Chronicles of Riddick', 'RoboCop', 'Speed Racer', 'How Do You Know', 'Knight and Day', 'Oblivion', 'Star Wars: Episode III - Revenge of the Sith', 'Star Wars: Episode II - Attack of the Clones', 'Monsters, Inc.', 'The Wolverine', 'Star Wars: Episode I - The Phantom Menace', 'The Croods', 'Asterix at the Olympic Games', 'Windtalkers', "The Huntsman: Winter's War", 'Teenage Mutant Ninja Turtles', 'Gravity', "Dante's Peak", 'Teenage Mutant Ninja Turtles: Out of the Shadows', 'Fantastic Four', 'Night at the Museum', 'San Andreas', 'Tomorrow Never Dies', 'The Patriot', "Ocean's Twelve", 'Mr. & Mrs. Smith', 'Insurgent', 'The Aviator', "Gulliver's Travels", 'The Green Hornet', '300: Rise of an Empire', 'The Smurfs', 'Home on the Range', 'Allegiant', 'Real Steel', 'The Smurfs 2', 'Speed 2: Cruise Control', "Ender's Game", 'Live Free or Die Hard', 'The Lord of the Rings: The Fellowship of the Ring', 'Around the World in 80 Days', 'Ali', 'The Cat in the Hat', 'I, Robot', 'Kingdom of Heaven', 'Stuart Little', 'The Princess and the Frog', 'The Martian', 'The Island', 'Town & Country', 'Gone in Sixty Seconds', 'Gladiator', 'Minority Report', 'Harry Potter and the Chamber of Secrets', 'Casino Royale', 'Planet of the Apes', 'Terminator 2: Judgment Day', 'Public Enemies', 'American Gangster', 'True Lies', 'The Taking of Pelham 1 2 3', 'Little Fockers', 'The Other Guys', 'Eraser', 'Django Unchained', 'The Hunchback of Notre Dame', "The Emperor's New Groove", 'The Expendables 2', 'National Treasure', 'Eragon', 'Where the Wild Things Are', 'Epic', 'The Tourist', 'End of Days', 'Blood Diamond', 'The Wolf of Wall Street', 'Batman Forever', 'Starship Troopers', 'Cloud Atlas', "Legend of the Guardians: The Owls of Ga'Hoole", 'Catwoman', 'Hercules', 'Treasure Planet', 'Land of the Lost', 'The Expendables 3', 'Point Break', 'Son of the Mask', 'In the Heart of the Sea', 'The Adventures of Pluto Nash', 'Green Zone', 'The Peanuts Movie', 'The Spanish Prisoner', 'The Mummy Returns', 'Gangs of New York', 'The Flowers of War', "Surf's Up", 'The Stepford Wives', 'Black Hawk Down', 'The Campaign', 'The Fifth Element', 'Sex and the City 2', 'The Road to El Dorado', 'Ice Age: Continental Drift', 'Cinderella', 'The Lovely Bones', 'Finding Nemo', 'The Lord of the Rings: The Return of the King', 'The Lord of the Rings: The Two Towers', 'Seventh Son', 'Lara Croft: Tomb Raider', 'Transcendence', 'Jurassic Park III', 'Rise of the Planet of the Apes', 'The Spiderwick Chronicles', 'A Good Day to Die Hard', 'The Alamo', 'The Incredibles', 'Cutthroat Island', 'Percy Jackson & the Olympians: The Lightning Thief', 'Men in Black', 'Toy Story 2', 'Unstoppable', 'Rush Hour 2', 'What Lies Beneath', 'Cloudy with a Chance of Meatballs', 'Ice Age: Dawn of the Dinosaurs', 'The Secret Life of Walter Mitty', "Charlie's Angels", 'The Departed', 'Mulan', 'Tropic Thunder', 'The Girl with the Dragon Tattoo', 'Die Hard: With a Vengeance', 'Sherlock Holmes', 'Ben-Hur', 'Atlantis: The Lost Empire', 'Alvin and the Chipmunks: The Road Chip', 'Valkyrie', "You Don't Mess with the Zohan", 'Pixels', 'A.I. Artificial Intelligence', 'The Haunted Mansion', 'Contact', 'Hollow Man', 'The Interpreter', 'Percy Jackson: Sea of Monsters', 'Lara Croft Tomb Raider: The Cradle of Life', 'Now You See Me 2', 'The Saint', 'Spy Game', 'Mission to Mars', 'Rio', 'Bicentennial Man', 'Volcano', "The Devil's Own", 'K-19: The Widowmaker', 'Conan the Barbarian', 'Cinderella Man', 'The Nutcracker: The Untold Story', 'Seabiscuit', 'Twister', 'Cast Away', 'Happy Feet', 'The Bourne Supremacy', 'Air Force One', "Ocean's Eleven", 'The Three Musketeers', 'Hotel Transylvania', 'Enchanted', 'Safe House', '102 Dalmatians', 'Tower Heist', 'The Holiday', 'Enemy of the State', "It's Complicated", "Ocean's Thirteen", 'Open Season', 'Divergent', 'Enemy at the Gates', 'The Rundown', 'Last Action Hero', 'Memoirs of a Geisha', 'The Fast and the Furious: Tokyo Drift', 'Arthur Christmas', 'Meet Joe Black', 'Collateral Damage', 'All That Jazz', 'Mirror Mirror', 'Scott Pilgrim vs. the World', 'The Core', 'Nutty Professor II: The Klumps', 'Scooby-Doo', 'Dredd', 'Click', 'Creepshow', 'Cats & Dogs 2 : The Revenge of Kitty Galore', 'Jumper', 'Hellboy II: The Golden Army', 'Zodiac', 'The 6th Day', 'Bruce Almighty', 'The Expendables', 'Mission: Impossible', 'The Hunger Games', 'The Hangover Part II', 'Batman Returns', 'Over the Hedge', 'Lilo & Stitch', "Charlotte's Web", 'Deep Impact', 'RED 2', 'The Longest Yard', 'Alvin and the Chipmunks: Chipwrecked', 'Grown Ups 2', 'Get Smart', "Something's Gotta Give", 'Shutter Island', 'Four Christmases', 'Robots', 'Face/Off', 'Bedtime Stories', 'Road to Perdition', 'Just Go with It', 'Con Air', 'Eagle Eye', 'Cold Mountain', 'The Book of Eli', 'Flubber', 'The Haunting', 'Space Jam', 'The Pink Panther', 'The Day the Earth Stood Still', 'Conspiracy Theory', 'Fury', 'Six Days Seven Nights', 'Yogi Bear', 'Spirit: Stallion of the Cimarron', 'Zookeeper', 'Lost in Space', 'The Manchurian Candidate', 'Déjà Vu', 'Hotel Transylvania 2', 'Fantasia 2000', 'The Time Machine', 'Mighty Joe Young', 'Swordfish', 'The Legend of Zorro', 'What Dreams May Come', 'Little Nicky', 'The Brothers Grimm', 'Mars Attacks!', 'Evolution', 'The Edge', 'Surrogates', 'Thirteen Days', 'Daylight', 'Walking With Dinosaurs', 'Battlefield Earth', 'Looney Tunes: Back in Action', 'Nine', 'Timeline', 'The Postman', 'Babe: Pig in the City', 'The Last Witch Hunter', 'Red Planet', 'Arthur and the Invisibles', 'Oceans', 'A Sound of Thunder', 'Pompeii', 'Top Cat Begins', 'A Beautiful Mind', 'The Lion King', 'Journey 2: The Mysterious Island', 'Cloudy with a Chance of Meatballs 2', 'Red Dragon', 'Hidalgo', 'Jack and Jill', '2 Fast 2 Furious', 'The Little Prince', 'The Invasion', 'The Adventures of Rocky & Bullwinkle', 'The Secret Life of Pets', 'The League of Extraordinary Gentlemen', 'Despicable Me 2', 'Independence Day', 'The Lost World: Jurassic Park', 'Madagascar', 'Children of Men', 'X-Men', 'Wanted', 'The Rock', 'Ice Age: The Meltdown', '50 First Dates', 'Hairspray', 'Exorcist: The Beginning', 'Inspector Gadget', 'Now You See Me', 'Grown Ups', 'The Terminal', 'Hotel for Dogs', 'Vertical Limit', "Charlie Wilson's War", 'Shark Tale', 'Dreamgirls', 'Be Cool', 'Munich', 'Tears of the Sun', 'Killers', 'The Man from U.N.C.L.E.', 'Spanglish', 'Monster House', 'Bandits', 'First Knight', 'Anna and the King', 'Immortals', 'Hostage', 'Titan A.E.', 'Hollywood Homicide', 'Soldier', 'Carriers', 'Monkeybone', 'Flight of the Phoenix', 'Unbreakable', 'Minions', 'Sucker Punch', 'Snake Eyes', 'Sphere', 'The Angry Birds Movie', "Fool's Gold", 'Funny People', 'The Kingdom', 'Talladega Nights: The Ballad of Ricky Bobby', 'Dr. Dolittle 2', 'Braveheart', 'Jarhead', 'The Simpsons Movie', 'The Majestic', 'Driven', 'Two Brothers', 'The Village', 'Doctor Dolittle', 'Signs', 'Shrek 2', 'Cars', 'Runaway Bride', 'xXx', 'The SpongeBob Movie: Sponge Out of Water', 'Ransom', 'Inglourious Basterds', 'Hook', 'Die Hard 2', 'S.W.A.T.', 'Vanilla Sky', 'Lady in the Water', 'AVP: Alien vs. Predator', 'Alvin and the Chipmunks: The Squeakquel', 'We Were Soldiers', 'Olympus Has Fallen', 'Star Trek: Insurrection', 'Battle: Los Angeles', 'Big Fish', 'Wolf', 'War Horse', 'The Monuments Men', 'The Abyss', 'Wall Street: Money Never Sleeps', 'Dracula Untold', 'The Siege', 'Stardust', 'Seven Years in Tibet', 'The Dilemma', 'Bad Company', 'Doom', 'I Spy', 'Underworld: Awakening', 'Rock of Ages', "Hart's War", 'Killer Elite', 'Rollerball', 'Ballistic: Ecks vs. Sever', 'Hard Rain', 'Osmosis Jones', "Legends of Oz: Dorothy's Return", 'Blackhat', 'Sky Captain and the World of Tomorrow', 'Basic Instinct 2', 'Escape Plan', 'The Legend of Hercules', 'The Sum of All Fears', 'The Twilight Saga: Eclipse', 'The Score', 'Despicable Me', 'Money Train', 'Ted 2', 'Agora', 'Mystery Men', 'Hall Pass', 'The Insider', 'The Finest Hours', 'Body of Lies', 'Dinner for Schmucks', 'Abraham Lincoln: Vampire Hunter', 'Entrapment', 'The X Files', 'The Last Legion', 'Saving Private Ryan', 'Need for Speed', 'What Women Want', 'Ice Age', 'Dreamcatcher', 'Lincoln', 'The Matrix', 'Apollo 13', 'The Santa Clause 2', 'Les Misérables', "You've Got Mail", 'Step Brothers', 'The Mask of Zorro', 'Due Date', 'Unbroken', 'Space Cowboys', 'Cliffhanger', 'Broken Arrow', 'The Kid', 'World Trade Center', 'Mona Lisa Smile', 'The Dictator', 'Eyes Wide Shut', 'Annie', 'Focus', 'This Means War', 'Blade: Trinity', 'Red Dawn', 'Primary Colors', 'Resident Evil: Retribution', 'Death Race', 'The Long Kiss Goodnight', 'Proof of Life', 'Zathura: A Space Adventure', 'Fight Club', 'We Are Marshall', 'Hudson Hawk', 'Lucky Numbers', 'I, Frankenstein', 'Oliver Twist', 'Elektra', 'Sin City: A Dame to Kill For', 'Random Hearts', 'Everest', 'Perfume: The Story of a Murderer', 'Austin Powers in Goldmember', 'Astro Boy', 'Jurassic Park', 'Wyatt Earp', 'Clear and Present Danger', 'Dragon Blade', 'Little Man', 'U-571', 'The American President', 'The Love Guru', '3000 Miles to Graceland', 'The Hateful Eight', 'Blades of Glory', 'Hop', '300', 'Meet the Fockers', 'Marley & Me', 'The Green Mile', 'Wild Hogs', 'Chicken Little', 'Gone Girl', 'The Bourne Identity', 'GoldenEye', "The General's Daughter", 'The Truman Show', 'The Prince of Egypt', 'Daddy Day Care', '2 Guns', 'Cats & Dogs', 'The Italian Job', 'Two Weeks Notice', 'Antz', 'Couples Retreat', 'Days of Thunder', 'Cheaper by the Dozen 2', 'Maze Runner: The Scorch Trials', 'Eat Pray Love', 'The Family Man', 'RED', 'Any Given Sunday', 'The Horse Whisperer', 'Collateral', 'The Scorpion King', 'Ladder 49', 'Jack Reacher', 'Deep Blue Sea', 'This Is It', 'Contagion', 'Kangaroo Jack', 'Coraline', 'The Happening', 'Man on Fire', 'The Shaggy Dog', 'Starsky & Hutch', 'Jingle All the Way', 'Hellboy', 'A Civil Action', 'ParaNorman', 'The Jackal', 'Paycheck', 'Up Close & Personal', 'The Tale of Despereaux', 'The Tuxedo', 'Under Siege 2: Dark Territory', 'Jack Ryan: Shadow Recruit', 'Joy', 'London Has Fallen', 'Alien: Resurrection', 'Shooter', 'The Boxtrolls', 'Practical Magic', 'The Lego Movie', 'Miss Congeniality 2: Armed and Fabulous', 'Reign of Fire', 'Gangster Squad', 'Year One', 'Invictus', 'State of Play', 'Duplicity', 'My Favorite Martian', 'The Sentinel', 'Planet 51', 'Star Trek: Nemesis', 'Intolerable Cruelty', 'Trouble with the Curve', 'Edge of Darkness', 'The Relic', 'Analyze That', 'Righteous Kill', 'Mercury Rising', 'The Soloist', 'The Legend of Bagger Vance', 'Almost Famous', 'Garfield: A Tail of Two Kitties', 'xXx: State of the Union', 'Priest', 'Sinbad: Legend of the Seven Seas', 'Event Horizon', 'Dragonfly', 'The Black Dahlia', 'Flyboys', 'The Last Castle', 'Supernova', "Winter's Tale", 'The Mortal Instruments: City of Bones', 'Meet Dave', 'Dark Water', 'Edtv', 'Inkheart', 'The Spirit', 'Mortdecai', 'In the Name of the King: A Dungeon Siege Tale', 'Beyond Borders', 'The Monkey King 2', 'The Great Raid', 'Deadpool', 'Holy Man', 'American Sniper', 'Goosebumps', 'Just Like Heaven', 'The Flintstones in Viva Rock Vegas', 'Rambo III', 'Leatherheads', 'The Ridiculous 6', 'Did You Hear About the Morgans?', 'The Internship', 'Resident Evil: Afterlife', 'Red Tails', "The Devil's Advocate", "That's My Boy", 'DragonHeart', 'After the Sunset', 'Ghost Rider: Spirit of Vengeance', "Captain Corelli's Mandolin", 'The Pacifier', 'Walking Tall', 'Forrest Gump', 'Alvin and the Chipmunks', 'Meet the Parents', 'Pocahontas', 'Superman', 'The Nutty Professor', 'Hitch', 'George of the Jungle', 'American Wedding', 'Captain Phillips', 'Date Night', 'Casper', 'The Equalizer', 'Maid in Manhattan', 'Crimson Tide', 'The Pursuit of Happyness', 'Flightplan', 'Disclosure', 'City of Angels', 'Kill Bill: Vol. 1', 'Bowfinger', 'Kill Bill: Vol. 2', 'Tango & Cash', 'Death Becomes Her', 'Shanghai Noon', 'Executive Decision', "Mr. Popper's Penguins", 'The Forbidden Kingdom', 'Free Birds', 'Alien³', 'Evita', 'Ronin', 'The Ghost and the Darkness', 'Paddington', 'The Watch', 'The Hunted', 'Instinct', 'Stuck on You', 'Semi-Pro', 'The Pirates! In an Adventure with Scientists!', 'Changeling', 'Chain Reaction', 'The Fan', 'The Phantom of the Opera', 'Elizabeth: The Golden Age', 'Æon Flux', 'Gods and Generals', 'Turbulence', 'Imagine That', 'Muppets Most Wanted', 'Thunderbirds', 'Burlesque', 'A Very Long Engagement', 'Lolita', 'D-Tox', 'Blade II', 'Seven Pounds', 'Bullet to the Head', 'The Godfather: Part III', 'Elizabethtown', 'You, Me and Dupree', 'Superman II', 'Gigli', "All the King's Men", 'Shaft', 'Anastasia', 'Moulin Rouge!', 'Domestic Disturbance', 'Black Mass', 'Flags of Our Fathers', 'Law Abiding Citizen', 'Grindhouse', 'Beloved', 'Lucky You', 'Catch Me If You Can', 'Zero Dark Thirty', 'The Break-Up', 'Mamma Mia!', "Valentine's Day", 'The Dukes of Hazzard', 'The Thin Red Line', 'The Change-Up', 'Man on the Moon', 'Casino', 'From Paris with Love', 'Bulletproof Monk', 'Me, Myself & Irene', 'Barnyard', 'Deck the Halls', 'The Twilight Saga: New Moon', 'Shrek', 'The Adjustment Bureau', 'Robin Hood: Prince of Thieves', 'Jerry Maguire', 'Ted', 'As Good as It Gets', 'Patch Adams', 'Anchorman 2: The Legend Continues', 'Mr. Deeds', 'Super 8', 'Erin Brockovich', 'How to Lose a Guy in 10 Days', '22 Jump Street', 'Interview with the Vampire', 'Yes Man', 'Central Intelligence', 'Stepmom', "Daddy's Home", 'Into the Woods', 'Inside Man', 'Payback', 'Congo', 'We Bought a Zoo', 'Knowing', 'Failure to Launch', 'The Ring Two', 'Crazy, Stupid, Love.', 'Garfield', 'Christmas with the Kranks', 'Moneyball', 'Outbreak', 'Non-Stop', 'Race to Witch Mountain', 'V for Vendetta', 'Shanghai Knights', 'Curious George', 'Herbie Fully Loaded', "Don't Say a Word", 'Hansel & Gretel: Witch Hunters', 'Unfaithful', 'I Am Number Four', 'Syriana', '13 Hours: The Secret Soldiers of Benghazi', 'The Book of Life', 'Firewall', 'Absolute Power', 'G.I. Jane', 'The Game', 'Silent Hill', 'The Replacements', 'American Reunion', 'The Negotiator', 'Into the Storm', 'Beverly Hills Cop III', 'Gremlins 2: The New Batch', 'The Judge', 'The Peacemaker', 'Resident Evil: Apocalypse', 'Bridget Jones: The Edge of Reason', 'Out of Time', 'On Deadly Ground', 'The Adventures of Sharkboy and Lavagirl', 'The Beach', 'Raising Helen', 'Ninja Assassin', 'For Love of the Game', 'Striptease', 'Marmaduke', 'Hereafter', 'Murder by Numbers', 'Assassins', 'Hannibal Rising', 'The Story of Us', 'The Host', 'Basic', 'Blood Work', 'The International', 'Escape from L.A.', 'The Iron Giant', 'The Life Aquatic with Steve Zissou', 'Free State of Jones', 'The Life of David Gale', 'Man of the House', 'Run All Night', 'Eastern Promises', 'Into the Blue', 'The Messenger: The Story of Joan of Arc', 'Your Highness', 'Dream House', 'Mad City', "Baby's Day Out", 'The Scarlet Letter', 'Fair Game', 'Domino', 'Jade', 'Gamer', 'Beautiful Creatures', 'Death to Smoochy', 'Zoolander 2', 'The Big Bounce', 'What Planet Are You From?', 'Drive Angry', 'Street Fighter: The Legend of Chun-Li', 'The One', 'Th

In [69]:
# Finding the close match of the movie name taken as input from the user
find_close_match = difflib.get_close_matches(movie_name, all_movie_names)
print(find_close_match)

['Titanic', 'Trance', 'Maniac']

In [70]:
close_match = find_close_match[0]
print(close_match)

Titanic

In [72]:
# Finding the index of the movie with title
movie_index = df[df.title == close_match]["index"].values[0]
print(movie_index)

25

In [77]:
# Getting a list of similar movies based on a given movie
similarity_score = list(enumerate(similarity[movie_index]))
print(similarity_score)

[(0, 0.042849260959502256), (1, 0.0), (2, 0.011467364105495693), (3, 0.010046067299207014), (4, 0.010913900929666012), (5, 0.013271868195005245), (6, 0.0), (7, 0.044276351205847934), (8, 0.0), (9, 0.011052967674011078), (10, 0.040774737457045525), (11, 0.005154880168301485), (12, 0.0), (13, 0.011810642378201048), (14, 0.011135108727728622), (15, 0.010700980101090706), (16, 0.010727286350311038), (17, 0.0), (18, 0.0), (19, 0.058321349267840134), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0030136767341105873), (25, 1.0), (26, 0.0), (27, 0.035917907722692974), (28, 0.005803448123074126), (29, 0.017798015596744536), (30, 0.012912217205854762), (31, 0.011014776597901378), (32, 0.010369537913084386), (33, 0.017063631264570202), (34, 0.02704944297060011), (35, 0.0), (36, 0.0), (37, 0.049954284113239336), (38, 0.01143873602257278), (39, 0.0), (40, 0.0), (41, 0.005589882450477922), (42, 0.0), (43, 0.005898442690409995), (44, 0.013809733743104848), (45, 0.01978396131348192), (46, 0.023089304958972642), (47, 0.0372299993276412), (48, 0.01148424939752516), (49, 0.11503079796465221), (50, 0.007339389244272502), (51, 0.0), (52, 0.034668679888094585), (53, 0.0), (54, 0.03479584610112342), (55, 0.028057008606403686), (56, 0.0), (57, 0.0), (58, 0.019260417052999825), (59, 0.0), (60, 0.015019446073636825), (61, 0.007569638706172237), (62, 0.0), (63, 0.010357804791894224), (64, 0.02441883121784362), (65, 0.009174262745461691), (66, 0.0), (67, 0.0), (68, 0.0), (69, 0.01230279810058616), (70, 0.011004607844422318), (71, 0.0), (72, 0.0), (73, 0.0), (74, 0.0), (75, 0.0), (76, 0.005851051039380289), (77, 0.003122675107328781), (78, 0.01587830506351622), (79, 0.010126904778387515), (80, 0.0034585065802924574), (81, 0.014495976248351618), (82, 0.00948668223893311), (83, 0.007817654812105891), (84, 0.011689479459229995), (85, 0.0), (86, 0.025639871767385792), (87, 0.03413092601756141), (88, 0.0), (89, 0.0), (90, 0.0), (91, 0.0), (92, 0.0), (93, 0.005580427949924979), (94, 0.012454828175767388), (95, 0.044089343554847456), (96, 0.08817670269624489), (97, 0.0024830633059495853), (98, 0.06233609088771174), (99, 0.00557051111876728), (100, 0.015716990642844913), (101, 0.013798139217630026), (102, 0.0), (103, 0.003282538044568501), (104, 0.009192125066407326), (105, 0.02425681925763852), (106, 0.03156254034175994), (107, 0.0), (108, 0.005787046985764752), (109, 0.008149065882104007), (110, 0.027137078409370238), (111, 0.011837001499023569), (112, 0.0031585654236239886), (113, 0.0), (114, 0.0), (115, 0.0), (116, 0.04839233557922966), (117, 0.010243058536105146), (118, 0.0), (119, 0.0033615828299815155), (120, 0.0), (121, 0.010535876731941955), (122, 0.006277970308259292), (123, 0.005385117592827929), (124, 0.0), (125, 0.0053014963763363485), (126, 0.01033985087586537), (127, 0.006109758506011243), (128, 0.01807025103903195), (129, 0.0), (130, 0.0), (131, 0.0), (132, 0.0), (133, 0.0), (134, 0.005475924526023212), (135, 0.008120290075325264), (136, 0.0), (137, 0.0), (138, 0.04190695561991919), (139, 0.029198017354080615), (140, 0.009265706894006536), (141, 0.0), (142, 0.11838847957751894), (143, 0.0), (144, 0.011249102882021137), (145, 0.0026363009364389813), (146, 0.03396994727919764), (147, 0.005225185852208087), (148, 0.023548397651456516), (149, 0.0638043283410441), (150, 0.0), (151, 0.0), (152, 0.0), (153, 0.005414645768987308), (154, 0.04089092645582204), (155, 0.010637517743877414), (156, 0.024638244848584904), (157, 0.0033569072331851007), (158, 0.0), (159, 0.011992878106901545), (160, 0.0), (161, 0.0), (162, 0.0), (163, 0.034121685927412444), (164, 0.0173141541962097), (165, 0.0035299427884999497), (166, 0.006792103689137105), (167, 0.06066814467912833), (168, 0.0), (169, 0.0), (170, 0.014056126050498843), (171, 0.03646378409526667), (172, 0.017648778548114936), (173, 0.0), (174, 0.010064606395554176), (175, 0.01068899112933489), (176, 0.09472769132005915), (177, 0.0), (178, 0.06854447828390522), (179, 0.0), (180, 0.05885013286305692), (181, 0.0), (182, 0.010769964792822863), (183, 0.011638946225794373), (184, 0.0), (185, 0.005798676414672125), (186, 0.005048311675661681), (187, 0.025264784088040965), (188, 0.005881262903909656), (189, 0.0035207086049510363), (190, 0.0), (191, 0.0), (192, 0.0031896896430047158), (193, 0.0), (194, 0.0), (195, 0.0), (196, 0.0), (197, 0.0), (198, 0.0), (199, 0.0), (200, 0.006013537932102896), (201, 0.018337940768795514), (202, 0.0), (203, 0.04489976282021112), (204, 0.0057821796583682255), (205, 0.0), (206, 0.0), (207, 0.0), (208, 0.0), (209, 0.005980325641541611), (210, 0.0), (211, 0.0), (212, 0.005523555122866163), (213, 0.006335181699660117), (214, 0.0032669869048523596), (215, 0.006091484933882649), (216, 0.05352088184338699), (217, 0.0056054963072527265), (218, 0.0068169840826639615), (219, 0.03323759228685398), (220, 0.0349747544318558), (221, 0.0), (222, 0.009311848569937959), (223, 0.0), (224, 0.0), (225, 0.0), (226, 0.02687258741792554), (227, 0.042222762483214084), (228, 0.03161534990153744), (229, 0.0), (230, 0.0), (231, 0.03693384925618592), (232, 0.011614865932546299), (233, 0.0), (234, 0.0), (235, 0.0), (236, 0.0032187476778428566), (237, 0.0029767050835668965), (238, 0.03772178581611297), (239, 0.008068123148311268), (240, 0.005884629018830928), (241, 0.010851639707755066), (242, 0.024845411623073806), (243, 0.0), (244, 0.007575655018453007), (245, 0.005004958572539803), (246, 0.0029703594985059346), (247, 0.005409632373209549), (248, 0.009415346787437204), (249, 0.09498018720867243), (250, 0.10070176966728618), (251, 0.0), (252, 0.030468514743824025), (253, 0.009387362992560122), (254, 0.01046201607148346), (255, 0.0), (256, 0.02386332704840048), (257, 0.0031471559072234613), (258, 0.01096451584831882), (259, 0.0051526428449492866), (260, 0.011048598120214501), (261, 0.006628804883261598), (262, 0.06268406770597823), (263, 0.0), (264, 0.0030187971006895107), (265, 0.0), (266, 0.02427806972498145), (267, 0.002622225394884812), (268, 0.011344391944153468), (269, 0.016811823277843776), (270, 0.0154983163844231), (271, 0.04208023277930428), (272, 0.0072451617381676095), (273, 0.005454240533536365), (274, 0.0034196792432880855), (275, 0.005469561738063076), (276, 0.0), (277, 0.005792474436863987), (278, 0.005102665527804905), (279, 0.08894947756410568), (280, 0.028990495864389117), (281, 0.0030471319892998667), (282, 0.04344378415429302), (283, 0.007529092102879541), (284, 0.007578057684900515), (285, 0.0), (286, 0.03474208615287537), (287, 0.0855359091010837), (288, 0.017366757838325114), (289, 0.0), (290, 0.0059752268450791275), (291, 0.005233976466071952), (292, 0.009165418064594125), (293, 0.011706221580388776), (294, 0.0), (295, 0.01990649302293436), (296, 0.0), (297, 0.0931117842119575), (298, 0.09014095125690445), (299, 0.0), (300, 0.0048021000011540405), (301, 0.003287355491283182), (302, 0.010983344298485069), (303, 0.03871350557294238), (304, 0.0), (305, 0.011169879926239383), (306, 0.0), (307, 0.005612795021441079), (308, 0.004944362856524863), (309, 0.0), (310, 0.0733718184016256), (311, 0.0), (312, 0.00787205707403752), (313, 0.009929874272564575), (314, 0.009519226169524959), (315, 0.039486305651174294), (316, 0.11879207685844574), (317, 0.0029156201006567744), (318, 0.05133114511541345), (319, 0.0), (320, 0.0), (321, 0.0), (322, 0.006000535931068796), (323, 0.029322675076517896), (324, 0.011742671734420167), (325, 0.0), (326, 0.02365194665918715), (327, 0.003356072722126918), (328, 0.0), (329, 0.043879636581873306), (330, 0.045034884300970086), (331, 0.0), (332, 0.0047126765933444914), (333, 0.028175917033571467), (334, 0.005418466483623983), (335, 0.021633584857467324), (336, 0.0), (337, 0.0037931178445090087), (338, 0.026783565742430616), (339, 0.0), (340, 0.03375970282747866), (341, 0.0), (342, 0.030606592381547178), (343, 0.0), (344, 0.004801913759694117), (345, 0.0064679217752472), (346, 0.04659467879012351), (347, 0.014847350915751862), (348, 0.0), (349, 0.0030006028757322803), (350, 0.04214181267871598), (351, 0.09601987660900405), (352, 0.0), (353, 0.0), (354, 0.019591865864036644), (355, 0.006064974345812653), (356, 0.03571690403911386), (357, 0.0032153375781836663), (358, 0.011774963599696738), (359, 0.0), (360, 0.008705811216581389), (361, 0.0), (362, 0.025791239583400377), (363, 0.029243652524431514), (364, 0.005065085289898681), (365, 0.02453789660158999), (366, 0.005091613623926898), (367, 0.005659022904721569), (368, 0.0), (369, 0.01369276656778818), (370, 0.0), (371, 0.010543478579587904), (372, 0.00544300277091085), (373, 0.0), (374, 0.02700577484867789), (375, 0.0), (376, 0.008436372208953498), (377, 0.030973192508383072), (378, 0.008227717950009494), (379, 0.010833636490659333), (380, 0.009645658587419158), (381, 0.046745322803090315), (382, 0.014095704416752997), (383, 0.0029808490312071027), (384, 0.003122642165845418), (385, 0.0), (386, 0.02094613928587557), (387, 0.01688135849943674), (388, 0.006100869184580785), (389, 0.005647802698244332), (390, 0.012801143392070542), (391, 0.018540710569898363), (392, 0.005484613707156479), (393, 0.0), (394, 0.0), (395, 0.08623026935866933), (396, 0.009505702318379862), (397, 0.007558190373022304), (398, 0.005746765230100317), (399, 0.023029843071814684), (400, 0.07807477934110839), (401, 0.0), (402, 0.0056791120899395454), (403, 0.0), (404, 0.008004003220778794), (405, 0.015673524988923732), (406, 0.014753478981421781), (407, 0.002836056848785729), (408, 0.009148201182148749), (409, 0.0018367157949118588), (410, 0.002966177655530335), (411, 0.0), (412, 0.06744212338423375), (413, 0.007774003696468063), (414, 0.0), (415, 0.0), (416, 0.03185967533948817), (417, 0.0), (418, 0.013099844857710801), (419, 0.012077460289341346), (420, 0.0), (421, 0.009191800558108107), (422, 0.0), (423, 0.0), (424, 0.005689622224365428), (425, 0.006335651690181267), (426, 0.0), (427, 0.0), (428, 0.0), (429, 0.0), (430, 0.0), (431, 0.0), (432, 0.04347056084454867), (433, 0.006344991142977542), (434, 0.0033497645152072144), (435, 0.045018670328576905), (436, 0.013620659008376007), (437, 0.00641575132170978), (438, 0.05410689719299024), (439, 0.11317975752102442), (440, 0.010155127214732598), (441, 0.0), (442, 0.004961807089157374), (443, 0.03582422211072814), (444, 0.017842078025981305), (445, 0.007015866551144297), (446, 0.016411557209318663), (447, 0.006331306578276947), (448, 0.0024386682958397045), (449, 0.00530974927279258), (450, 0.0), (451, 0.016553229831197756), (452, 0.025376540954743638), (453, 0.0), (454, 0.1658990773043873), (455, 0.0405078739381747), (456, 0.0029142658294415594), (457, 0.007263894839184042), (458, 0.0), (459, 0.012193169285738015), (460, 0.020605925474518474), (461, 0.0), (462, 0.008765329669360993), (463, 0.011048329410765476), (464, 0.013179822099981605), (465, 0.02797850162924399), (466, 0.0), (467, 0.0), (468, 0.016398126822845714), (469, 0.0), (470, 0.010138444786925483), (471, 0.03484646731063575), (472, 0.005574101392596028), (473, 0.0), (474, 0.0030273476394477865), (475, 0.0026833780494898442), (476, 0.018967844746196155), (477, 0.008501479901495558), (478, 0.005715806337719946), (479, 0.0), (480, 0.011432612011568954), (481, 0.0), (482, 0.009371056111350676), (483, 0.05771723478268021), (484, 0.002786903191716048), (485, 0.014139225644717649), (486, 0.0), (487, 0.004972908900087912), (488, 0.0), (489, 0.0), (490, 0.012886070086174308), (491, 0.009275416048323656), (492, 0.0), (493, 0.010969239837287486), (494, 0.014172144835065759), (495, 0.0), (496, 0.047531923517385874), (497, 0.006632288356037594), (498, 0.0), (499, 0.0), (500, 0.005457101970930221), (501, 0.013037604954158987), (502, 0.004464991801154417), (503, 0.0), (504, 0.0), (505, 0.00558252603668481), (506, 0.0), (507, 0.032605627718228364), (508, 0.0), (509, 0.0), (510, 0.0087894601378875), (511, 0.011420492122465048), (512, 0.01952315011043669), (513, 0.01383951274720188), (514, 0.0), (515, 0.006616034726759292), (516, 0.018977014890484936), (517, 0.017637633133082177), (518, 0.04642549355291471), (519, 0.04182393141384611), (520, 0.0), (521, 0.003358373289770467), (522, 0.0), (523, 0.005827342000787645), (524, 0.05261246039261542), (525, 0.0), (526, 0.003423035176478259), (527, 0.0), (528, 0.0066653593413481226), (529, 0.029934928858330594), (530, 0.014519533139684404), (531, 0.010223741276144194), (532, 0.0126823636907606), (533, 0.0), (534, 0.03892144333393674), (535, 0.009792963948804065), (536, 0.010029002925864618), (537, 0.0030635576094321447), (538, 0.008850499188818799), (539, 0.03650620158563636), (540, 0.007409282518865152), (541, 0.008855955156078316), (542, 0.03581463134209983), (543, 0.0), (544, 0.008801240715838128), (545, 0.0080514183432517), (546, 0.0), (547, 0.005920442066758293), (548, 0.0), (549, 0.0), (550, 0.011033985187937129), (551, 0.02947075408642679), (552, 0.002795161405212058), (553, 0.009054083853896156), (554, 0.03835813917374199), (555, 0.007319015694229404), (556, 0.0027036364881553566), (557, 0.0031804216718514205), (558, 0.0), (559, 0.009394876429946351), (560, 0.0), (561, 0.002199124464810758), (562, 0.00893913811679464), (563, 0.0), (564, 0.008813186027864276), (565, 0.03188909899838787), (566, 0.0), (567, 0.007817654034197277), (568, 0.005527112940272053), (569, 0.0), (570, 0.005726882461923778), (571, 0.00824383651834475), (572, 0.0), (573, 0.017732661903966742), (574, 0.0055247949179133525), (575, 0.0760984510329956), (576, 0.007716352027541314), (577, 0.0), (578, 0.010813251433255764), (579, 0.022716961894379585), (580, 0.00544373879962044), (581, 0.043924485426227046), (582, 0.0), (583, 0.028385888820360205), (584, 0.04289652461984929), (585, 0.0026352410049704893), (586, 0.002762340088239479), (587, 0.04107092261263899), (588, 0.004019825565701051), (589, 0.0031457858999045674), (590, 0.019289472960123656), (591, 0.01983199832781537), (592, 0.0027769727069041007), (593, 0.23007271072115248), (594, 0.005795383444405329), (595, 0.01000178282196317), (596, 0.005920006425367655), (597, 0.03566891008710574), (598, 0.010814978254772635), (599, 0.0028020622300485454), (600, 0.0067686597359976446), (601, 0.006232722878430096), (602, 0.006341857424198713), (603, 0.034696500328128564), (604, 0.0), (605, 0.0), (606, 0.003061573939162355), (607, 0.005724479252075375), (608, 0.005408510261768605), (609, 0.051123394298257734), (610, 0.0), (611, 0.01946603320491591), (612, 0.011539025238441032), (613, 0.005479071634097281), (614, 0.0), (615, 0.010142401522204416), (616, 0.0), (617, 0.00281033384826124), (618, 0.0), (619, 0.0), (620, 0.008705171603361244), (621, 0.018077549140095933), (622, 0.10374165072398073), (623, 0.0), (624, 0.0), (625, 0.010799890270749417), (626, 0.006408687566064559), (627, 0.0), (628, 0.04278600926890032), (629, 0.0164911031432442), (630, 0.006447017586761083), (631, 0.0), (632, 0.0093487844705933), (633, 0.03847414373321924), (634, 0.0), (635, 0.0034676036838822187), (636, 0.0), (637, 0.011781424625763719), (638, 0.017835613560064946), (639, 0.0), (640, 0.0), (641, 0.003160568334183648), (642, 0.002967943181262977), (643, 0.030699455592373803), (644, 0.005711345731802593), (645, 0.009127793885447164), (646, 0.0), (647, 0.00797248701901723), (648, 0.05858830817605603), (649, 0.0), (650, 0.00276376170538275), (651, 0.03548481534951611), (652, 0.010057367251510019), (653, 0.007440120872133778), (654, 0.005970162335892793), (655, 0.006138536750542352), (656, 0.1260624612880309), (657, 0.0), (658, 0.01604580280814076), (659, 0.00578359947504368), (660, 0.020895552204820055), (661, 0.0), (662, 0.002862882517377905), (663, 0.0034811373693117553), (664, 0.052518074172896535), (665, 0.006399170078813246), (666, 0.0392549025490723), (667, 0.0031687627592968176), (668, 0.010845367253578783), (669, 0.00628898713991167), (670, 0.010554760929720285), (671, 0.002915914161446336), (672, 0.014618474378630598), (673, 0.0), (674, 0.0), (675, 0.0), (676, 0.00299107004779065), (677, 0.008525030953752677), (678, 0.003602835559934915), (679, 0.027578815578180343), (680, 0.007787326701412855), (681, 0.00940249002503338), (682, 0.007547729982240078), (683, 0.005162379607317756), (684, 0.002805608267431489), (685, 0.0031622924216221614), (686, 0.010945458083660537), (687, 0.0), (688, 0.007357859822402331), (689, 0.01285931890673895), (690, 0.027751449922457795), (691, 0.010149387259072664), (692, 0.0), (693, 0.018965518300840187), (694, 0.019086271028257808), (695, 0.004990060010400898), (696, 0.0354352040771153), (697, 0.014503523724086718), (698, 0.0034257009719491412), (699, 0.0), (700, 0.01102484125946821), (701, 0.0), (702, 0.0), (703, 0.006932133989734713), (704, 0.0), (705, 0.007015723773803581), (706, 0.0), (707, 0.0), (708, 0.01007399516099763), (709, 0.0465153680241176), (710, 0.007258861594154037), (711, 0.004893398264743019), (712, 0.04534364248345213), (713, 0.0110862248592042), (714, 0.009056052497372125), (715, 0.0), (716, 0.008701632108068798), (717, 0.020521241070142394), (718, 0.0045363924324356006), (719, 0.0), (720, 0.10752741389011593), (721, 0.0), (722, 0.0), (723, 0.004764847349790978), (724, 0.008735171996047338), (725, 0.0), (726, 0.0), (727, 0.0), (728, 0.0), (729, 0.0031550764612399067), (730, 0.0), (731, 0.0061349796728268815), (732, 0.006402501705074643), (733, 0.03181796533461144), (734, 0.0), (735, 0.005942030353216007), (736, 0.004990431215944015), (737, 0.008865308245974354), (738, 0.015903389080143257), (739, 0.00533221405167573), (740, 0.0), (741, 0.03031080071896814), (742, 0.009760442493162085), (743, 0.0028082887353195925), (744, 0.0), (745, 0.04053480495091553), (746, 0.0), (747, 0.009031441851676134), (748, 0.0), (749, 0.030676780396452528), (750, 0.0), (751, 0.007528033980523538), (752, 0.012774312895172535), (753, 0.005826950187561706), (754, 0.0), (755, 0.005738662720744838), (756, 0.007293399515102793), (757, 0.011266051338563215), (758, 0.009546242428017751), (759, 0.028271934677972288), (760, 0.029356612084487182), (761, 0.00820745498857917), (762, 0.00924139070334141), (763, 0.0032580957075201843), (764, 0.0033448685376759593), (765, 0.11360426444934431), (766, 0.02695842949331822), (767, 0.0031897084195046366), (768, 0.005743945710837995), (769, 0.0), (770, 0.0), (771, 0.08851018054570885), (772, 0.002906737403253216), (773, 0.026274637647135793), (774, 0.025837288846603773), (775, 0.016678343014029692), (776, 0.023095477731988397), (777, 0.010317860931534433), (778, 0.04476418962362351), (779, 0.02036829479583869), (780, 0.0), (781, 0.0), (782, 0.01640324670399714), (783, 0.01085286408764304), (784, 0.0033882000702094373), (785, 0.010837875230316641), (786, 0.0), (787, 0.019958652533109494), (788, 0.010372523329839596), (789, 0.03546724428317247), (790, 0.0), (791, 0.012430038461894884), (792, 0.01718480733389713), (793, 0.007823886532560054), (794, 0.004610547888254964), (795, 0.009905970114894452), (796, 0.0), (797, 0.0), (798, 0.025578484139800114), (799, 0.0), (800, 0.0028058706757914265), (801, 0.009046783599763327), (802, 0.0), (803, 0.0), (804, 0.003195215874729641), (805, 0.005264686802880303), (806, 0.010874639854444213), (807, 0.009262492973741772), (808, 0.008837491528689808), (809, 0.018587307824855653), (810, 0.04117109071642583), (811, 0.007378489082820745), (812, 0.003099905984541137), (813, 0.0), (814, 0.018517145057598383), (815, 0.025151823790291065), (816, 0.00782387945197373), (817, 0.006939182944964827), (818, 0.05442074366374522), (819, 0.0), (820, 0.0), (821, 0.0055556335469279135), (822, 0.011749397490727391), (823, 0.008845945502911113), (824, 0.016910228104515184), (825, 0.029628782786352593), (826, 0.018193920878235514), (827, 0.009562818185718684), (828, 0.0), (829, 0.012184551951128521), (830, 0.005055091034738166), (831, 0.0455087237715321), (832, 0.0), (833, 0.0), (834, 0.009075783776998492), (835, 0.0), (836, 0.0), (837, 0.011691333140298372), (838, 0.0), (839, 0.0026923837560126045), (840, 0.04180857715164567), (841, 0.01191188554995407), (842, 0.012600318444381708), (843, 0.0), (844, 0.008823884765850783), (845, 0.0101649670786146

In [79]:
# Sorting similar movies in terms of similarity score in descending order
sorted_similarity_score = sorted(similarity_score, key=lambda x: x[1], reverse=True)
print(sorted_similarity_score)

[(25, 1.0), (593, 0.23007271072115248), (454, 0.1658990773043873), (1081, 0.1603512882331143), (2011, 0.13803443166572782), (3631, 0.1333839815786052), (4133, 0.13183140853614747), (656, 0.1260624612880309), (1985, 0.12349759621747015), (2036, 0.12348320550112098), (316, 0.11879207685844574), (142, 0.11838847957751894), (2449, 0.11814094328522082), (846, 0.11610782635112266), (49, 0.11503079796465221), (765, 0.11360426444934431), (439, 0.11317975752102442), (2245, 0.11276113457467148), (720, 0.10752741389011593), (1362, 0.10696934437645385), (1629, 0.10631964670577464), (1500, 0.10616709183973469), (972, 0.10565080846258224), (622, 0.10374165072398073), (2955, 0.10279003651035283), (2175, 0.10248148361918039), (250, 0.10070176966728618), (4231, 0.09751550112290146), (1089, 0.09711335392784962), (2008, 0.09668793526881608), (961, 0.09638190705612416), (351, 0.09601987660900405), (3533, 0.09505757385996452), (249, 0.09498018720867243), (176, 0.09472769132005915), (2152, 0.09435255537205345), (2098, 0.09393990159229), (1515, 0.09335120633178544), (297, 0.0931117842119575), (3837, 0.09168912383632888), (1409, 0.09094793853103433), (298, 0.09014095125690445), (1690, 0.08949132929901657), (279, 0.08894947756410568), (4375, 0.08894592926655571), (771, 0.08851018054570885), (96, 0.08817670269624489), (4640, 0.08803718493955182), (2212, 0.08783504818201643), (2701, 0.08739722352470489), (1566, 0.08712004410470256), (395, 0.08623026935866933), (1401, 0.08554643761379609), (287, 0.0855359091010837), (872, 0.08496894606373423), (1380, 0.08473224630337553), (1269, 0.08383128075258156), (1514, 0.0829646872639986), (2946, 0.08257525539312248), (2850, 0.08252590624184605), (883, 0.08249509199175924), (2452, 0.08038722263532333), (1891, 0.07825521601732897), (400, 0.07807477934110839), (3212, 0.07769647924378437), (980, 0.07737931974349034), (2369, 0.07653667483863852), (575, 0.0760984510329956), (4258, 0.07414114721057297), (2870, 0.07378435087499059), (310, 0.0733718184016256), (3698, 0.07300934940851761), (2661, 0.072228391610393), (4514, 0.07189868326148557), (1989, 0.07156139417128705), (1689, 0.0714902234590532), (2254, 0.07107506346834663), (2455, 0.07075730967840471), (964, 0.07050683081152877), (1842, 0.07038664147680408), (2373, 0.07010390513727795), (3231, 0.0697048059416609), (2058, 0.06956192798248466), (1490, 0.06859821899626026), (1990, 0.06854742512106687), (178, 0.06854447828390522), (1845, 0.06843875074116348), (2004, 0.0677258234423861), (1492, 0.06747339382316987), (412, 0.06744212338423375), (1185, 0.06685738337683653), (1834, 0.06576080423070789), (2354, 0.0657309835332578), (984, 0.06539089528592841), (4780, 0.06526592944593135), (3314, 0.06455699455870219), (2826, 0.06438598849707483), (2403, 0.06410973222232412), (149, 0.0638043283410441), (2181, 0.06338314425460564), (262, 0.06268406770597823), (1940, 0.06247519846585349), (98, 0.06233609088771174), (1902, 0.06211561921858297), (2809, 0.061795051097649906), (1665, 0.06166657998155064), (2702, 0.061591857448795875), (2935, 0.061514942578480294), (167, 0.06066814467912833), (4142, 0.0604838424759067), (3097, 0.060432326004149856), (2721, 0.06040378091804946), (910, 0.059164525127258075), (180, 0.05885013286305692), (3695, 0.05862526609418119), (3896, 0.05860283915708961), (648, 0.05858830817605603), (19, 0.058321349267840134), (3280, 0.058030919131731966), (3566, 0.057756243952318306), (3794, 0.0577534460598403), (1067, 0.05772344629083427), (483, 0.05771723478268021), (3043, 0.057667825126862034), (2751, 0.057543085514884816), (4192, 0.05728430749142682), (3763, 0.05680221735611127), (3302, 0.05622147469238273), (2040, 0.05617275164111353), (1675, 0.056090680463922085), (2577, 0.05579461837542428), (1599, 0.05549887357913268), (3198, 0.05535855168024682), (3053, 0.0547857932031343), (1427, 0.05463743676841868), (818, 0.05442074366374522), (1331, 0.054149518487475436), (438, 0.05410689719299024), (1305, 0.05396123362633387), (2706, 0.05375518791127599), (3956, 0.05375152281971336), (216, 0.05352088184338699), (2143, 0.05339508789969569), (3484, 0.0529059670671303), (3983, 0.052795717179832655), (1374, 0.05266666681211456), (524, 0.05261246039261542), (664, 0.052518074172896535), (4608, 0.05250845570027509), (2438, 0.05237655936413273), (1247, 0.05220368717885194), (4147, 0.05216711764817653), (3675, 0.05195991803524089), (4682, 0.05189872182793619), (1537, 0.051796395550448446), (1667, 0.051587152423450994), (1342, 0.051339994758537254), (318, 0.05133114511541345), (2788, 0.051227377855525454), (609, 0.051123394298257734), (3439, 0.05110596284613303), (4724, 0.05098488693747919), (1329, 0.05094547755609693), (3195, 0.05061426064876317), (1122, 0.05051222622411742), (1032, 0.050440721930929765), (37, 0.049954284113239336), (867, 0.04983781392160243), (2612, 0.0493097217715285), (2663, 0.04920633910790426), (4513, 0.048940739051785316), (2362, 0.04884493701802897), (1134, 0.048698913340941744), (4051, 0.04867019597160813), (4350, 0.04863414366271319), (2554, 0.048587352872263026), (1775, 0.048549965048533456), (116, 0.04839233557922966), (1784, 0.04826568970299194), (1918, 0.04808981902878716), (1633, 0.047776094956303417), (4188, 0.04775671710553146), (3537, 0.04753928934345297), (496, 0.047531923517385874), (1160, 0.04736157935538327), (2416, 0.04692582628910526), (2080, 0.046801713779658444), (381, 0.046745322803090315), (346, 0.04659467879012351), (709, 0.0465153680241176), (518, 0.04642549355291471), (3850, 0.0464005811680957), (4557, 0.04632530142890248), (2932, 0.04630330853877783), (2381, 0.04594387932567558), (1953, 0.045823181987238545), (3345, 0.04580663200464264), (4100, 0.04570828110675927), (4200, 0.0455669487052604), (1068, 0.045538324024318046), (831, 0.0455087237715321), (2741, 0.04547058576240084), (2124, 0.04541169994143828), (3949, 0.04536134145340584), (712, 0.04534364248345213), (1410, 0.045137236143758155), (4561, 0.045100940678785416), (3347, 0.04505242722955999), (330, 0.045034884300970086), (435, 0.045018670328576905), (2748, 0.044953848056491816), (203, 0.04489976282021112), (778, 0.04476418962362351), (2818, 0.044763637311374636), (3568, 0.044681889725342344), (1578, 0.044495190078480726), (1928, 0.04437299464719276), (7, 0.044276351205847934), (2486, 0.044265224744405654), (1092, 0.04419635483747663), (1202, 0.04411112554155973), (95, 0.044089343554847456), (854, 0.043938735566669454), (581, 0.043924485426227046), (329, 0.043879636581873306), (3322, 0.043725103029583136), (1646, 0.04350993167382872), (432, 0.04347056084454867), (282, 0.04344378415429302), (1213, 0.04344052159825305), (3790, 0.04337848940351331), (1510, 0.043375443193988915), (1065, 0.04303539010330465), (2587, 0.04300232433594178), (3126, 0.042985104636534634), (584, 0.04289652461984929), (0, 0.042849260959502256), (4269, 0.042804033625004255), (628, 0.04278600926890032), (1774, 0.04261736269669839), (4696, 0.04260491038234709), (1873, 0.04258965148978156), (2402, 0.04252472507559883), (3745, 0.04247533508857209), (1115, 0.04238898659378082), (227, 0.042222762483214084), (350, 0.04214181267871598), (271, 0.04208023277930428), (1458, 0.042072738588529515), (999, 0.04206415479006218), (2810, 0.041969560050653706), (138, 0.04190695561991919), (1701, 0.04189745774009955), (4020, 0.041857829652938765), (3186, 0.04185344582950084), (519, 0.04182393141384611), (840, 0.04180857715164567), (2620, 0.04176319406467094), (2129, 0.04166625471221644), (1330, 0.041595918227435476), (2018, 0.04159353354458313), (3311, 0.04158926995752313), (2276, 0.04141918077860839), (1831, 0.041407274715004216), (810, 0.04117109071642583), (587, 0.04107092261263899), (4586, 0.040971473072765954), (154, 0.04089092645582204), (4019, 0.040843529308330635), (2174, 0.04078821382299222), (10, 0.040774737457045525), (2340, 0.04073957741215683), (4516, 0.04069190659237087), (3116, 0.04063936058053698), (868, 0.040556986994847034), (745, 0.04053480495091553), (3556, 0.04051963849178409), (455, 0.0405078739381747), (1910, 0.04043926403741191), (2571, 0.040413033991609976), (2348, 0.040388366875960625), (4313, 0.04036615633982822), (4707, 0.040362292171226555), (1445, 0.04027354907663171), (2939, 0.04016563079913729), (1986, 0.040074512806070266), (2313, 0.04004078484348432), (3861, 0.03999061232361559), (2239, 0.03995233776009917), (3487, 0.03994127100666287), (1384, 0.03987445840810759), (3591, 0.03982269696693957), (943, 0.03982118618088147), (2524, 0.039803027258256435), (4440, 0.03973250919806203), (3750, 0.039651934449074826), (3641, 0.03957605922125161), (315, 0.039486305651174294), (3705, 0.03935482378407127), (2304, 0.03933379120953984), (666, 0.0392549025490723), (995, 0.039218856906363196), (3598, 0.03897827348743121), (534, 0.03892144333393674), (4482, 0.03889427741520179), (303, 0.03871350557294238), (1737, 0.03862575985521748), (3401, 0.03858587901728064), (633, 0.03847414373321924), (902, 0.038470950728899), (898, 0.038402209438955996), (2097, 0.03836941739727541), (554, 0.03835813917374199), (1369, 0.038335361992548625), (2793, 0.03826558683861873), (3377, 0.03824167586816391), (1640, 0.0381924725109877), (3661, 0.038188163511891624), (1996, 0.038151754394305015), (3139, 0.03814386567365192), (3215, 0.03811697215116264), (1286, 0.038096137815364875), (4000, 0.038055263117685714), (1887, 0.03791935429093314), (238, 0.03772178581611297), (1255, 0.03767814875180583), (921, 0.037659012738029574), (4124, 0.037645691334299874), (4448, 0.03749334457567804), (1348, 0.03737591989812537), (1952, 0.03723032308479518), (47, 0.0372299993276412), (1446, 0.03722136760601281), (3978, 0.03717983432325659), (3064, 0.03715702156541112), (2580, 0.03708262326356265), (1718, 0.037005490093273655), (231, 0.03693384925618592), (2388, 0.0369017179958105), (3806, 0.03683743653378551), (2020, 0.03683248982413245), (3587, 0.03674249207302367), (1422, 0.036727092778757346), (3278, 0.0367140718833936), (1224, 0.036693990353428706), (4103, 0.03666411759494769), (1394, 0.036663689236501845), (1148, 0.036644431981460064), (4380, 0.036610599056582864), (4233, 0.03656615372041622), (2404, 0.0365393870565017), (539, 0.03650620158563636), (3348, 0.03649883470066481), (2179, 0.03649368777901037), (171, 0.03646378409526667), (1017, 0.03645450885543108), (1461, 0.036365245373473985), (1090, 0.036343787253333315), (1337, 0.036343009700307544), (2450, 0.03626004524171984), (4700, 0.03622251770447374), (2336, 0.036216113606909316), (2305, 0.03611194636561889), (1654, 0.03610261850911482), (3684, 0.03596940134965033), (2928, 0.03595112828787568), (27, 0.035917907722692974), (2572, 0.035909244304123865), (443, 0.03582422211072814), (542, 0.03581463134209983), (3827, 0.03575293970257029), (1366, 0.035743812043709154), (356, 0.03571690403911386), (3048, 0.03568838900754703), (3288, 0.03568621011189097), (597, 0.03566891008710574), (1513, 0.03554833590452448), (1079, 0.03550009671420469), (1042, 0.035489016766744416), (651, 0.03548481534951611), (1082, 0.035476121558381375), (789, 0.03546724428317247), (3687, 0.03546580442160331), (696, 0.0354352040771153), (1383, 0.03540655006755616), (1296, 0.03538316891222706), (3473, 0.03538081894435842), (2096, 0.03531386567229851), (2912, 0.03530223669119933), (2076, 0.03521976346117447), (2752, 0.03521035759796795), (869, 0.035141420294383996), (3733, 0.03508128656861888), (3720, 0.035053358714642824), (1132, 0.035037644664264726), (2989, 0.035030276686013356), (4559, 0.035000532282232225), (2945, 0.03497855566527095), (220, 0.0349747544318558), (2474, 0.034909710422900184), (3791, 0.03489071219834342), (471, 0.03484646731063575), (3553, 0.034804677794499195), (54, 0.03479584610112342), (3885, 0.03478394360295613), (286, 0.03474208615287537), (603, 0.034696500328128564), (52, 0.034668679888094585), (1205, 0.03466757388787231), (1536, 0.03461184321753464), (1308, 0.03458609197286287), (2392, 0.034524947231672765), (3589, 0.03438660019734535), (2708, 0.034249353083945604), (2255, 0.034243176477011694), (3262, 0.034237317334995965), (4232, 0.034186041923915444), (3270, 0.03417954623479241), (3638, 0.034147070525972906), (4324, 0.03413971906370027), (87, 0.03413092601756141), (163, 0.034121685927412444), (4316, 0.03398709476727308), (146, 0.03396994727919764), (2419, 0.033944158851586886), (2424, 0.033809040528726984), (340, 0.03375970282747866), (2435, 0.03375588252045489), (3984, 0.03366340065358281), (4196, 0.033595067775771974), (3655, 0.033519782267506265), (3514, 0.03341561246404048), (1765, 0.03339962517330569), (2753, 0.03338420689050034), (3889, 0.033372894137915304), (1824, 0.03335261379802214), (2747, 0.03333762317016554), (4511, 0.03330654443741023), (1630, 0.033304983138513315), (2315, 0.033257177619096384), (219, 0.03323759228685398), (1031, 0.033194290458716316), (1002, 0.033123335668393886), (3416, 0.033059699932766355), (2308, 0.03300612370676907), (2938, 0.03296293182791742), (1607, 0.032934676977370146), (1556, 0.032924062026024964), (2100, 0.03290112596546982), (3741, 0.03287540700433714), (4767, 0.032787710391781286), (4761, 0.032744210312792704), (4635, 0.032718681434289576), (1225, 0.032671605308582374), (507, 0.032605627718228364), (2052, 0.03257252205979836), (1452, 0.032484382455440663), (962, 0.03244090826441139), (3491, 0.03239555939497609), (2171, 0.0323526586319258), (2029, 0.03219723644342163), (4703, 0.03216119197242476), (1283, 0.03215654908046791), (1208, 0.03210445970319532), (2169, 0.032046847000446396), (3582, 0.03201448075476558), (3632, 0.031983934377830654), (3953, 0.031963793364547424), (3427, 0.03193225066234179), (565, 0.03188909899838787), (3798, 0.0318675835062746), (416, 0.03185967533948817), (4717, 0.03183659845539635), (2193, 0.03182188811645721), (733, 0.03181796533461144), (2279, 0.03178687625902291), (3260, 0.03178344154096262), (3899, 0.03175651536588179), (1198, 0.031715206517533165), (228, 0.03161534990153744), (106, 0.03156254034175994), (2492, 0.031480978479708766), (2012, 0.0314617342165312), (4775, 0.031419977000650925), (1623, 0.03138743696339781), (1000, 0.031192690859434342), (1714, 0.031192427116618387), (2657, 0.03119241908644924), (3704, 0.031154694660136234), (2981, 0.031087017807610744), (1853, 0.03103317471529457), (3343, 0.03100191231172268), (377, 0.030973192508383072), (1693, 0.030900634826196923), (2547, 0.030825945737553217), (3399, 0.0308151698028329), (2206, 0.030806016746309714), (2975, 0.03079300322850646), (1728, 0.0307720221958539), (1813, 0.03073477779527345), (643, 0.030699455592373803), (1975, 0.03069682344593217), (749, 0.030676780396452528), (899, 0.030664403825619836), (3046, 0.030630215162817633), (1489, 0.0306162662545313), (342, 0.030606592381547178), (3966, 0.030579662200260968), (981, 0.03057569316901894), (2596, 0.030508572560723826), (4011, 0.030491253806154903), (252, 0.030468514743824025), (3261, 0.030387407936789262), (4587, 0.03038279941877871), (741, 0.03031080071896814), (4632, 0.030296843235647485), (1561, 0.03023841041971786), (2557, 0.030042205050256312), (3009, 0.030033120742914893), (529, 0.029934928858330594), (1691, 0.02986471169697296), (3538, 0.029773683367429932), (3287, 0.029762036913256636), (4249, 0.02973588049031318), (4144, 0.029701937263903674), (4543, 0.029691590262007524), (1222, 0.029646299988492327), (2632, 0.029631046495703507), (825, 0.029628782786352593), (3513, 0.029624676840482637), (2767, 0.029610354850831036), (2163, 0.029600959995356994), (1433, 0.029521474328610707), (2283, 0.029472263738222954), (551, 0.02947075408642679), (4480, 0.02936300291445579), (760, 0.029356612084487182), (4628, 0.029345256575854607), (2494, 0.0293345363177301), (4024, 0.029327582359698144), (323, 0.029322675076517896), (903, 0.02926277849662861), (363, 0.029243652524431514), (2413, 0.02922828378459306), (4223, 0.029203622939217244), (139, 0.029198017354080615), (1745, 0.029005655338318684), (3177, 0.029003073271219218), (280, 0.028990495864389117), (1157, 0.028960244551265724), (4076, 0.028834900545208153), (2161, 0.02878821349268848), (1733, 0.02874748105150856), (1419, 0.028698246666621047), (1139, 0.028614124556369257), (1768, 0.02858986851587429), (2367, 0.028555623836183867), (3576, 0.02851479432408014), (3784, 0.028514635167011075), (3662, 0.028488881994144), (1413, 0.028422790204194307), (941, 0.028420525071936875), (583, 0.028385888820360205), (2462, 0.02838403748525131), (1153, 0.02837675904041517), (3626, 0.028345771575282726), (1193, 0.028345126606263697), (1747, 0.02833714862847224), (759, 0.028271934677972288), (4238, 0.02824678103771884), (3625, 0.028183088393620236), (333, 0.028175917033571467), (55, 0.028057008606403686), (4568, 0.027995618522500706), (465, 0.02797850162924399), (3032, 0.02789955378921746), (4575, 0.027893796238258675), (1925, 0.027859996879446514), (2263, 0.02785941287104338), (3159, 0.0278209922923604), (1110, 0.02779305039894372), (690, 0.027751449922457795), (1837, 0.027693220498101957), (2638, 0.027690022725422064), (4442, 0.027660484876546442), (4774, 0.02764621600467699), (2875, 0.02759361193000448), (679, 0.027578815578180343), (4798, 0.02757754025508836), (2323, 0.027561484413736233), (1590, 0.02752687894664422), (3857, 0.027462732419883687), (1250, 0.027442906226733486), (1943, 0.02728821233741785), (1592, 0.027285292059942873), (3581, 0.02722941352540005), (1077, 0.02722707040341232), (2383, 0.027205431333510274), (3620, 0.027178700692157238), (110, 0.027137078409370238), (3747, 0.027060700286545676), (34, 0.02704944297060011), (4486, 0.027041199376077144), (374, 0.02700577484867789), (766, 0.02695842949331822), (2518, 0.026947881149804346), (3403, 0.02693874764819812), (2758, 0.026917120974903615), (226, 0.02687258741792554), (1917, 0.02682975951997791), (4420, 0.02681487448377263), (338, 0.026783565742430616), (4627, 0.026765215904310996), (986, 0.026755688096518702), (2196, 0.026721370394899645), (4327, 0.026606257230837465), (1736, 0.02657693867946975), (3433, 0.026511056545854894), (4321, 0.026453977087164026), (4487, 0.026403953547806756), (4190, 0.026329271519248965), (2043, 0.026287852303369504), (773, 0.026274637647135793), (3651, 0.026253289862306687), (1816, 0.026096964446432617), (1154, 0.026096888989506545), (3303, 0.02604642800379169), (1300, 0.025912403797433065), (3507, 0.025895240585646743), (774, 0.025837288846603773), (1291, 0.02580884535312352), (2904, 0.025800260803944222), (2736, 0.025796452324414923), (362, 0.025791239583400377), (3515, 0.025772637272103344), (3894, 0.025744956141459045), (3299, 0.02568232313980514), (86, 0.025639871767385792), (4691, 0.025585293620220967), (798, 0.025578484139800114), (3886, 0.025395169490156144), (452, 0.025376540954743638), (3168, 0.025328927979543073), (4407, 0.025297159159545474), (187, 0.025264784088040965), (3067, 0.02520321928613968), (1852, 0.02518939953141141), (3906, 0.02515278730334309), (815, 0.025151823790291065), (2493, 0.025143127389879612), (2678, 0.025118906486607334), (4119, 0.025053851092208698), (2456, 0.025015284764117948), (2649, 0.024999932370914593), (4408, 0.02499407037913771), (2219, 0.024978668918823353), (2356, 0.024957324625667694), (3546, 0.02492505602751993), (1543, 0.024871066614666947), (3183, 0.02486766642615595), (242, 0.024845411623073806), (2856, 0.024845052473054303), (3366, 0.02474211307443796), (1183, 0.024691004977293964), (156, 0.024638244848584904), (1563, 0.024619376972150962), (365, 0.02453789660158999), (2611, 0.024478415652145986), (64, 0.02441883121784362), (2071, 0.02436749025683089), (2750, 0.024355207867565974), (1982, 0.024316866109822338), (266, 0.02427806972498145), (105, 0.02425681925763852), (1974, 0.02419201573883032), (1602, 0.024190197663320676), (3996, 0.024098996631358366), (4283, 0.024000479939925445), (1261, 0.023981244239867295), (4433, 0.023946262838636278), (4630, 0.023897812667031768), (256, 0.02386332704840048), (4176, 0.023844732638463605), (3482, 0.023812437437556896), (3916, 0.023729801754606726), (2151, 0.023673746659147364), (1107, 0.023661388528272456), (2858, 0.023660441977698968), (326, 0.02365194665918715), (4216, 0.0236468

In [80]:
# Printing the names of similar movies based on similarity score
print("Movies suggested : \n")

i=1

for movie in sorted_similarity_score:
  index = movie[0]
  title_from_index = df[df.index == index]["title"].values[0]
  if(i<30):
    print(i, ".", title_from_index)
    i+=1

Movies suggested :

1 . Titanic
2 . The Dilemma
3 . The Day the Earth Stood Still
4 . Revolutionary Road
5 . Cheri
6 . Heavenly Creatures
7 . Plush
8 . Primary Colors
9 . The Bridge of San Luis Rey
10 . Saving Silverman
11 . Gangs of New York
12 . Flushed Away
13 . Sense and Sensibility
14 . Stuck on You
15 . The Great Gatsby
16 . Almost Famous
17 . Shutter Island
18 . The Brothers Bloom
19 . Contagion
20 . The Blind Side
21 . Little Black Book
22 . This Is the End
23 . The Host
24 . Body of Lies
25 . Romance & Cigarettes
26 . Ladyhawke
27 . The Aviator
28 . The Believer
29 . The Phantom

**Movie Recommendation System**

In [81]:
# Taking the input name of movie from the user
movie_name = input("Enter the name of your favourite movie: ")

# Creating a list with all movie names given in the dataset
all_movie_names = df["title"].tolist()

# Finding the close match of the movie name taken as input from the user
find_close_match = difflib.get_close_matches(movie_name, all_movie_names)

# Getting the closest matching movie
close_match = find_close_match[0]

# Finding the index of the movie with title
movie_index = df[df.title == close_match]["index"].values[0]

# Getting a list of similar movies based on a given movie
similarity_score = list(enumerate(similarity[movie_index]))

# Sorting similar movies in terms of similarity score in descending order
sorted_similarity_score = sorted(similarity_score, key=lambda x: x[1], reverse=True)

# Printing the names of similar movies based on similarity score
print("Movies suggested : \n")

i=1

for movie in sorted_similarity_score:
  index = movie[0]
  title_from_index = df[df.index == index]["title"].values[0]
  if(i<30):
    print(i, ".", title_from_index)
    i+=1

Enter the name of your favourite movie: Interstellar
Movies suggested :

1 . Interstellar
2 . The Dark Knight Rises
3 . The Matrix
4 . The Martian
5 . Dear Frankie
6 . Argo
7 . The Matrix Revolutions
8 . The Matrix Reloaded
9 . The Terminator
10 . Armageddon
11 . Terminator Genisys
12 . Contact
13 . Terminator Salvation
14 . The Killer Inside Me
15 . Gandhi, My Father
16 . The Tree of Life
17 . Get Smart
18 . Back to the Future
19 . Terminator 3: Rise of the Machines
20 . The Prestige
21 . Batman Begins
22 . Dragonslayer
23 . WarGames
24 . Little Nicky
25 . Superman III
26 . The Other Side of Heaven
27 . House at the End of the Street
28 . Good Deeds
29 . Mortal Kombat: Annihilation